### ISSUE TITLE
Highlighting in search results case sensitive

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#1000]
I noticed that our seach function does not properly highlight all hits in the results page:
they are only highlighted if the caps match exactly
The SMF codes does it properly, ours does not

Example:
If I search for the String "Tiny"

The words are only highlighted in the search results if the string matches EXACTLY

The string Tiny is found and correctly highlighted: [b][color=orange]Tiny[/color][/b]

The string tiny is found but not highlighted: It should highlight [b][color=orange]tiny[/color][/b]
The string tinyportal is found but not highlighted: It should highlight [b][color=orange]tiny[/color][/b]portal

**Comment by dragomano** [comment]
`TPdlmanager.php`, you need to replace
`preg_quote($what, '/').'/', '<span class="highlight">'.$what.'</span>'`
with
`preg_quote($what, '/').'/iu', '<span class="highlight">$0</span>'`

**Comment by Bopske** [comment]
thanks, fixed in #1009
