### ISSUE TITLE
Panels showing in modules admin section

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#132]
Ref TP 1.6.0
Panels / blocks appear to be showing when viewing Modules >TP List Images > Admin.

**Comment by Bopske** [comment]
It seems TPlistimages is not considered to be an admin task, since it is tpmod and not tpadmin.
Not sure how that works, I leave this one to you Tino...

**Comment by tinoest** [comment]
It’ll be a new set of options, or we just say it’s the same as tpadmin

**Comment by Bopske** [comment]
I would just use tpadmin: it is an admin function anyway, similar to managing articles...

**Comment by tinoest** [comment]
Fixed in #143
