### ISSUE TITLE
menu manager deletion bug

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#133]
Ref TP 1.6.0
Menu button remains in site navigation if menu is deleted and button was still active.

**Comment by Bopske** [comment]
Fixed by PR #140

**Comment by lurkalot** [comment]
Still allows you to choose and add a menu button item in menu's other than Internal.  Thing is, if you do add a menu button, and try to edit it afterwards, you can't. You also can't remove it.

**Comment by Bopske** [comment]
Removing should still work?

**Comment by Bopske** [comment]
Is now fixed with latest PR.

**Comment by lurkalot** [comment]
Thanks.  Seems to be working as expected now.
