### ISSUE TITLE
Latest fix for shoutbox prevents panels showing 

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#152]
Latest fix for shoutbox prevents panels showing on front page etc.  https://github.com/Tinyportal/TinyPortal/commit/e3cb2533759c506592c501f438e7da22c42c19e3

Relevant Post, https://www.tinyportal.net/index.php?topic=36128.msg294328#msg294328

**Comment by Bopske** [comment]
Maybe check this code from tportal.php?
There is another reason to suppress the blocks...

	// if admin specifies no blocks, no blocks are shown! likewise, if in admin or tpadmin screen, turn off blocks
	if (in_array($context['TPortal']['action'], array('help', 'moderate', 'theme', 'tpadmin', 'admin', 'ban', 'boardrecount', 'cleanperms', 'detailedversion', 'dumpdb', 'featuresettings', 'featuresettings2', 'findmember', 'maintain', 'manageattachments', 'manageboards', 'managecalendar', 'managesearch', 'membergroups', 'modlog', 'news', 'optimizetables', 'packageget', 'packages', 'permissions', 'pgdownload', 'postsettings', 'regcenter', 'repairboards', 'reports', 'serversettings', 'serversettings2', 'smileys', 'viewErrorLog', 'viewmembers')))
		$in_admin = true;
	if(($context['user']['is_admin'] && isset($_GET['noblocks'])) || ($context['TPortal']['hidebars_admin_only']=='1' && isset($in_admin)))
		tp_hidebars();
