### ISSUE TITLE
BBC editor needed for 2.1.  articles, downloads and shoutbox

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#164]
TPshout.php

everywhere where .gif files are used. 
Need to be adapted to 2.1 bbc definitions: a bit more then just replace with png files...

**Comment by Bopske** [comment]
Bit sure what to do with this. Tino do you think its feasible to use SCeditor? Or should we maintain the ‘old smileys’. Just for the shoutbox?

**Comment by tinoest** [comment]
We could switch to sceditor. It makes sense to do so tbf.

**Comment by Bopske** [comment]
Then I have to leave this to you . I would not know where to start tbh

**Comment by Bopske** [comment]
I updated the description: I now find that the bbc code editor is not working for 2.1 at all: not for articles and not for downloads or the shoutbox...

**Comment by tinoest** [comment]
I think I have fixed the articles and downloads, can you please test. Shoutbox is still outstanding to do.

**Comment by Bopske** [comment]
I saw the PR merged and I just tested on mij local 2.1 testsite as well as the online 2.0.15 and 2.1.
The behaviour of the bbc editor and the html editor is looking good, both in the articles and the downloads!

**Comment by lurkalot** [comment]
Just tested on 2.1 and bbc buttons not working on shoutbox for me.

**Comment by tinoest** [comment]
I didn’t say I had sorted the shoutbox...

**Comment by TPMick** [comment]
OK, sorry. Just read your note properly about it still being outstanding. My bad.

**Comment by Bopske** [comment]
I think this is now complete, so may be closed.
Let's wait for Mick to confirm

**Comment by tinoest** [comment]
@TPmick we ok to close this now?

**Comment by lurkalot** [comment]
Yep sorry missed this.  Seems fine this end.  I'll close it.  Thank you guys.
