### ISSUE TITLE
Add support for PHP 7.2 and PHP 7.3 

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#171]
TinyPortal now largely supports SMF2.1, we need to support PHP 7.2 and it makes sense to think about PHP 7.3 which is due soon.

**Comment by lurkalot** [comment]
Agreed it would be a good idea.  Is it me or do these new PHP versions have a shorter lifespan nowadays.

**Comment by Bopske** [comment]
What changes are needed for 7.2? It seems to work quite well atm

**Comment by tinoest** [comment]
It will be the is_countable on count types, I think the others I sorted in previous fixes. 

7.3 will be the issue with regex mainly

**Comment by tinoest** [comment]
Everything seems to working ok in PHP 7.2, 7.3 is still in beta and it seems ok in that also.
