### ISSUE TITLE
Adding an 'empty item' in TPdownloads result in errors

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#191]
I am getting this error when posting an empty item in TPdownloads...

Type of error: General 
2: filesize(): stat failed for C:\xampp\htdocs\forum/tp-downloads/- empty item -
 http://localhost/forum/index.php?action=tpmod;dl=adminitem10
 C:/xampp/htdocs/forum/Sources/TPdlmanager.php (Line 3287)

**Comment by Bopske** [comment]
I had a look at this one, but cannot find why it's not working.
When a download is created as an empty item the file name - empty item - is used.

This code is not working it seems, but I cannot find what's wrong with it....

'filesize' => (substr($row['file'],14)!='- empty item -') ? floor(filesize($boarddir.'/tp-downloads/'.$row['file']) / 1024) : '0',

**Comment by tinoest** [comment]
Should be 

`'filesize' => (substr($row['file'], 0, 14)!='- empty item -') ? floor(filesize($boarddir.'/tp-downloads/'.$row['file']) / 1024) : '0',`

I think

**Comment by Bopske** [comment]
Yep that was it. Fixed in PR #204
