### ISSUE TITLE
Member group colours for usernames, for TP and SMF 2.1

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#205]
At the moment the shoutbox, recent block or anywhere else TP that displays a username doesn't seem to show the group colour on the username, 

With exception of the User block, and stats block which do display it in the group colour.

**Comment by Bopske** [comment]
Tino, I added the membergroup colors in the shoutbox. For the blocks I am stuck. What source file should I use to populate a variable for the blocks? I am not sure what file is actually triggering the tpsubs.template.php...

I am thinking of using the simplecolorizer code as an example...

**Comment by tinoest** [comment]
It's included in the TPSubs.php file which is included by TPortal_init. 

Subs seems to be loads of individual functions and has logic which I think should be in the TPSubs.php rather than the template.

**Comment by Bopske** [comment]
Thanks, indeed there seems to be some 'inconsistency' sometimes between source and template code...
I'll see if I can get it to work...

**Comment by Bopske** [comment]
Alas... I am stuck and frustrated with it. I am leaving this alone: can't fix it...

**Comment by tinoest** [comment]
> Alas... I am stuck and frustrated with it. I am leaving this alone: can't fix it...

What is causing you issues? What did you get working and what didn't work?

**Comment by tinoest** [comment]
I think the best way would be to do it in the the ob_start callback. 

So have a preg_match that looks for $scripturl action=profile;u= or similar then add a style attribute as appropriate before the href.

**Comment by Bopske** [comment]
I created  a function in tpsubs.php to retrieve membergroup colors using the member ids in the recent block and called it from the tpsubs.template.php , 

Once you have the correct hex color code for the user it is easily added into a style element. 
I did basically the same in the shoutbox.

Then I just got completely mixed up in code: array definition and checking it in the template. 
I finally ended up scrapping the code cause I got completely lost...

**Comment by tinoest** [comment]
Do you have the function to get the membergroup colours still?

**Comment by tinoest** [comment]
Add this to tpAddCopy 

> `$user_match = '~href="' . preg_quote($scripturl) . '\?action=profile;u=(\d+)"~';
    if(preg_match_all($user_match, $buffer, $matches)) {
        $user_ids   = array_values(array_unique($matches[1]));
        foreach($user_ids as $id) {
            $user_colour    = '#FFFFFF';
            $user_replace   = '~href="' . preg_quote($scripturl) . '\?action=profile;u='.$id.'"~';
            $buffer         = preg_replace($user_replace, ' style="color:'.$user_colour.';" $0', $buffer);
        }
    }`

And work out the colour from the user_ids rather than my hard coded value. 

I can't seem to sort the styling on here...

**Comment by Bopske** [comment]
I dumped the code (in frustration).. this is nto syntactically correct, but it is what is was working on..

// retrieve membergroup color
function getmembercolor($ids)
	{
	global $user_info, $smcFunc, $modSettings, $scripturl;
	global $image_proxy_enabled, $image_proxy_secret, $boardurl;
	$request = $smcFunc['db_query']('', '
		SELECT mem.id_member, mgrp.online_color as mg_online_color, pgrp.online_color as pg_online_color
	    FROM {db_prefix}members AS mem
			LEFT JOIN {db_prefix}membergroups AS mgrp ON
			(mgrp.id_group = mem.id_group)
			LEFT JOIN {db_prefix}membergroups AS pgrp ON
			(pgrp.id_group = mem.id_post_group)
		    WHERE mem.id_member IN(' . implode(",",$members) . ')' 
	    );
	}
	$mcol = array();
	if($smcFunc['db_num_rows']($request) > 0)
	{
		while ($row = $smcFunc['db_fetch_assoc']($request)) {
            $row['memcolor'] = (!empty('mg_online_color') ? 'mg_online_color' : 'pg_online_color');
			$mcol[$row['id_member']] = $row;
		}
		$smcFunc['db_free_result']($request);
	}

	return $mcol;
