### ISSUE TITLE
Inlog TP via tpshouts admin lay-out problem

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#207]
I stumbled accross some sort of bug just now. See far I only see this in 2.1, both with strict mode on and off...

Steps to reproduce:
1. Log off from the forum
2. Log In
3. Now from the menu choose: TinyPortal > Manage TPShout (image 1)
4. Now an incorrect screen is displayed: the Side mneu is full screen and login box is pushed down. (image 2)
5. After logging in screen 3 is showing: there are TWO side menus
6. Klik on [Save] and the screen returns to normal (screen 4)

This can be reproduced over and over again in 2.1 I cannot reproduce it in 2.0.15..

**Comment by TPMick** [comment]
Not seeing this at all in 2.1  however it does happen in 2.0.15 for me.
![manageshout215](https://user-images.githubusercontent.com/6047983/48248422-23ac8d80-e3ef-11e8-9a9c-bb2b258d4578.png)
![manageshout2](https://user-images.githubusercontent.com/6047983/48248428-29a26e80-e3ef-11e8-986e-e4bd0c60cffd.png)

**Comment by tinoest** [comment]
I don't know what's causing it, template_layers is having the tpadm set twice. but you can get around it by changing the template_tpadm_above to this

`function template_tpadm_above()
{
    global $context, $txt;
    static $runOnce = false;

    if($runOnce == true) {
        return;
    }
    $runOnce = true;`

in TPsubs.template.php. Not pretty at all and doesn't solve the issue just stops it showing.
