### ISSUE TITLE
Themes block not showing thumbnail

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#235]
Noticed when using themes block running 1.6.1 on 2.1 the thumbnail image doesn't display in the block. It's looking for a gif image instead of the png  The correct thumbnail does however in the Themes block edit page.

It looks for 
/Themes/default/images/thumbnail.gif
Instead of 
/Themes/default/images/thumbnail.png

**Comment by Bopske** [comment]
Fixed
