### ISSUE TITLE
Add Check on Install for minimum PHP Version

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#266]
With recent changes by me the minimum PHP Version is now PHP 5.4. As function derefencing has been implmented. Along with the change to add Annoymous functions which were implemented in PHP 5.3 older versions of PHP should no longer be supported. 

This should be checked on installation to ensure that the package can be installed sucessfully.

**Comment by Bopske** [comment]
Agree, in the meantime, what TP Version introduced this change? I will add this minimum requirement to the docs as well...

**Comment by tinoest** [comment]
> Agree, in the meantime, what TP Version introduced this change? I will add this minimum requirement to the docs as well...

Looking at the blame, I would say around 1.5.0.

**Comment by Bopske** [comment]
Not looking to blame anyone of course... ;-) 

I has a similar issue some time ago with a TP forum that I upgraded to 1.6.1 and is turned out to be on 5.3 still.. So if I state on the docs site that starting 1.5.0 the minimum php requirement is 5.4 that would be correct?

**Comment by tinoest** [comment]
Sorry by looking at the blame. 

I mean the feature called git blame ( which lists the changes and who made them and when )

Yes that would be correct.

**Comment by Bopske** [comment]
Nice, still need to learn more about Git
