### ISSUE TITLE
WYSIWYG On/Off settings available in other users profiles

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#277]
When viewing another members profile, and logged in as regular user.  I noticed that if you click the Tinyportal dropdown menu in their profile 

Tinyportal > Articles > Settings. You see a setting where you can turn the WYSIWYG on or off, complete with save button.

Ref, https://www.tinyportal.net/index.php?topic=36198.msg295910#msg295910

**Comment by tinoest** [comment]
If we link to messages can we try to make sure they are not on a private board?

**Comment by lurkalot** [comment]
Yep, consider my wrist duly slapped.  I forgot it was a private board.
