### ISSUE TITLE
Shoutbox issues with SMF 2.1

### ISSUE THREAD

**Issue by Oldiesmann** [Tinyportal/TinyPortal#296]
Playing around with TP on the latest git build of SMF 2.1 and have run into some issues with the shoutbox:

1. The code to display bbcode buttons on the shoutbox for SMF 2.0 generates a bunch of "Undefined index" errors due to the old language strings not being defined anymore.
2. The code to display bbcode buttons on the shoutbox for SMF 2.1 also generates undefined index errors ("Undefined index: Underline", "Undefined index: Strikethrough", "Undefined index: Italic" and "Undefined index: Bold").
3. Smiley images and bbcode buttons aren't showing up on the shoutbox (but smileys do show up in the shouts themselves just fine). There is also an "Undefined index: smiley_set_default_ext" error which may be related.
4. For some reason my shouts are being duplicated.

This is with the second of the three layouts. I haven't tried the other two yet.

**Comment by tinoest** [comment]
Some of these are fixed in the PR still open. Others we are waiting for SMF to actually release RC1

Duplicate shouts I would guess is the recent change to forum_version.

**Comment by Oldiesmann** [comment]
Good to know. Just figured I'd let you know anyway :smiley:

**Comment by tinoest** [comment]
I can’t replicate the duplicate shouts with the latest version of TinyPortal from GitHub. 

Can you try it and let me know if it still occurs. 

If it’s all ok I’ll close this issue.

**Comment by tinoest** [comment]
Closing as can't replicate issue.
