### ISSUE TITLE
Incorrect integer value: 'NULL'

### ISSUE THREAD

**Issue by Moowalker** [Tinyportal/TinyPortal#304]
After upgrading my forum from 2.0.15 for 2.1RC1 and installing Tinyportal 1.6.2 I get the following error during TP installation

> Incorrect integer value: 'NULL' for column ``.``.`eventid` at row 1
> File: /home/infinite/public_html/Packages/temp/install.php
> Line: 379

I did uninstall TP 1.6.1 before doing the installation of TP 1.6.2

**Comment by tinoest** [comment]
Try changing https://github.com/Tinyportal/TinyPortal/blob/master/install.php#L314 to default => 0 

What version of MySQL are you using as this doesn't break for me.
