### ISSUE TITLE
Better layout SMF 2.1

### ISSUE THREAD

**Issue by mastum** [Tinyportal/TinyPortal#315]
![1](https://user-images.githubusercontent.com/1554203/53693993-53b9db00-3da8-11e9-86fb-2be825f02be1.png)

It should be

![2](https://user-images.githubusercontent.com/1554203/53693998-616f6080-3da8-11e9-9e84-80748d49a9c0.png)

Thanks for this great mod.

**Comment by TPMick** [comment]
You can choose that style per block or by panel style.  Try setting to catbg+windowbg2

**Comment by vort7u** [comment]
> Try setting to catbg+windowbg2

It should be "Front Panel" right?

I tried but the style does not change.

**Comment by lurkalot** [comment]
Sorry that was me under a different login.

Example if you look at my left and bottom blocks, https://cctestsite.info/testsite3/index.php

they are set to catbg+windowbg2 While the rest of the blocks are set to catbg+windowbg

**Comment by lurkalot** [comment]
> Try setting to catbg+windowbg2
> 
> It should be "Front Panel" right?
> I tried but the style does not change.

Depends if each block has its own style set, instead of using Panel style, that overrides the panel setting.  You need to check each block for the setting.

**Comment by vort7u** [comment]
Thanks for the help, I checked but I can not change ONLY the style of the front panel block.

**Comment by lurkalot** [comment]
Ok, not sure what you mean there. So you can change the other blocks, but not the front panel ones, or you can only change the front panels ones and not the others??

**Comment by Bopske** [comment]
I recognize the ‘issue’. It is due to the SMF default style for windowbg: we are using it both in 2.0 and 2.1 . Changing this in TP will affect layout in 2.0 negatively...

**Comment by lurkalot** [comment]
I guess this stems back to what tino mentioned a while back, about TP for 2.0 and 2.1 having their own stylesheets.   Seems to work ok for me as is, but when using  catbg+windowbg2 the padding between each block is slightly excessive imo.

**Comment by tinoest** [comment]
You can add a condition to use the function addInlineCss in SMF 2.1 to get 'around' the issue. Not pretty but it would work.

**Comment by vort7u** [comment]
> So you can change the other blocks, but not the front panel ones, or you can only change the front panels ones and not the others??

I can change other blocks but not the front panel.
I'm using SMF 2.1 RC1 with default theme, sorry I forgot I'm using TP 1.6.2...

**Comment by lurkalot** [comment]
> So you can change the other blocks, but not the front panel ones, or you can only change the front panels ones and not the others??
> 
> I can change other blocks but not the front panel.
> I'm using SMF 2.1 RC1 with default theme, sorry I forgot I'm using TP 1.6.2...

So am I and can change both.  Have you tried setting this style per a individual block?  or by the panel setting?

**Comment by vort7u** [comment]
>  Have you tried setting this style per a individual block? or by the panel setting?

Yes without success

**Comment by lurkalot** [comment]
OK, so these are blocks in your front panel, not articles or posts ?

**Comment by Bopske** [comment]
I guess not: the setting in the panels ONLY applies to blocks and that works as intended. Perhaps we should extend that functionality to also apply to articles and posts, but that is a different topic. I would suggest raising a topic in the TP support forum for that: this is not the place to discuss new feature requests...

**Comment by vort7u** [comment]
Are posts and I understood now, from Bopske's answer, that it is not possible to change the layout for posts and articles on front pannel.

**Comment by Bopske** [comment]
Atm only by manually changing the css for SMF.

In file index.css.
Find:
.generic_list_wrapper, .windowbg, #forumposts .approvebg, #forumposts .approvebg2 {
	background: #f0f4f7;
	margin: 12px 0 0 0;
	padding: 12px 16px;
	border: 1px solid #ddd;
	border-radius: 6px;
	box-shadow: 0 -2px 2px rgba(0, 0, 0, 0.1);
	overflow: auto;
}

And update the MARGIN to
	**margin: 6px 0 6px 0;**

**Comment by Bopske** [comment]
Of course we'll look into a more permanent solution, but with SMF2.1 still changing their css moving through RC phases we are shooting for a moving target atm..

**Comment by lurkalot** [comment]
I don't seem to have that problem on my testsite with the gap between the articles / post and the header bar.  However, It is showing icons beside them which it shouldn't, but that's another issue. https://cctestsite.info/testsite3/index.php  OK, turns out they were set in front panel settings. Turning them off reproduces the gap mentioned above.

**Comment by vort7u** [comment]
> I don't seem to have that problem on my testsite with the gap between the articles / post and the header bar.

Sorry but I'm the only one to see it?
![screenshot_2019-03-03 lts](https://user-images.githubusercontent.com/1554203/53696368-9094ca80-3dc6-11e9-947f-14a4469c59a5.png)

Posts are attached

**Comment by lurkalot** [comment]
Yes that's because I changed the layout to normal articles.  If you change it to articles + icons like I had it, you'll see there's no gap.

**Comment by lurkalot** [comment]
Take a look now.

**Comment by vort7u** [comment]
OK, so with "Layout type: normal articles" is normal to have this problem?

**Comment by lurkalot** [comment]
> OK, so with "Layout type: normal articles" is normal to have this problem?

No I don't think so.  Just trying to compare stuff atm.

**Comment by lurkalot** [comment]
> I guess not: the setting in the panels ONLY applies to blocks and that works as intended. Perhaps we should extend that functionality to also apply to articles and posts, but that is a different topic. I would suggest raising a topic in the TP support forum for that: this is not the place to discuss new feature requests...

mastum, what was suggested here would be  good idea, pop over to our support forum and we can thrash this out better over there, https://www.tinyportal.net/index.php?action=forum

**Comment by Bopske** [comment]
Mastum, I provided you with a fix already. Please try the suggested css change.

**Comment by Bopske** [comment]
Fixed by PR #314
