### ISSUE TITLE
Wysiwyg editor errors in useredit dlmanager (both 2.0 and 2.1)

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#324]
I found that the useredit function for the DL manager was not updated to the 2.1 layout. While doing so I found that the Wysiwyg editor is non-functional on that screen. The HTML editor is absent, and the BBC editor actually gives an error.

In 2.1 it throws error: 8: Undefined index: editor_id
https://test2.fjr-club.nl/index.php?action=tpmod;dl=useredit26
/home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPdlmanager.template.php (Line 845)

In 2.0 it breaks down with this error: Call to undefined function template_control_richedit()

This only happens in the screen that a user (non admin) uses to edit his own download...

**Comment by Bopske** [comment]
Tested in 2.0 and 2.1. In both environments the html version is working fine now, there is just an issue with the bbc left: when a download is created as user it is working fine, but when going into change mode in bbc the text is missing...

![2019-03-10_191144](https://user-images.githubusercontent.com/24902644/54089378-aa0ab900-4368-11e9-8495-f007dbbbece6.png)
![2019-03-10_191154](https://user-images.githubusercontent.com/24902644/54089379-ac6d1300-4368-11e9-8dd1-03776f319f78.png)

**Comment by tinoest** [comment]
@Bopske Should work now I think

**Comment by Bopske** [comment]
Almost there: Text is showing up now, it is just not saving the changes afterwards...

**Comment by tinoest** [comment]
I have a feeling this never worked... 

I’ll look at the saving tomorrow, it’ll be looking for the wrong post string.

**Comment by Bopske** [comment]
Afraid so: though it is funny it’s never reported as such..
