### ISSUE TITLE
No check to not display Article Category or Edit/Print Icons 

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#344]
In the Article Display checks you can't disable the  'posted in Portal features', Edit or Print text. This should be added so you can have a blank article.

**Comment by Bopske** [comment]
The options to remove edit links and print are set a t the global level for ALL articles. This works just fine IMO: why would you want this done on a per article basis? 

The 'posted in portal features' I do not understand? What are you referring to? Featured article? That I can set in each article...

**Comment by tinoest** [comment]
> The 'posted in portal features' I do not understand? What are you referring to? Featured article? That I can set in each article...

I mean the subject line I can't disable, you also might want to disable them on a per article basis.

**Comment by Bopske** [comment]
ok, not sure what to say...

**Comment by tinoest** [comment]
I was thinking when you have custom blocks or articles you don’t want people to be able to print easily. Although I know you can use the built in browser option.

**Comment by Bopske** [comment]
This only applies to articles , right? I personally do not see a need to control at article level, but I assume there is no harm either .

I would leave the general setting in place though, and use this to switch off display for ALL articles at once...

**Comment by tinoest** [comment]
Not required so closing
