### ISSUE TITLE
Unable to load the 'main' template.

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#352]
This happens on 2.0.0

Login as admin, then go in the menu to TinyPortal > Manage TPshout
You are presented with the login form for TinyPortal: enter password and  error message displays

Unable to load the 'main' template.

any other menu option in TP, the login does work

**Comment by tinoest** [comment]
This only occurs when you're not already logged in I take it?

**Comment by Bopske** [comment]
Correct.

**Comment by tinoest** [comment]
It's the checks on the settings list on the left hand side causing the issue. I am tempted to remove it from the drop down tbf unless you are logged in as admin.
