### ISSUE TITLE
Trying to change Shoutbox block results in  Fatal error: Uncaught Error: Call to a member function db_query() on null

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#353]
Fresh install of 2.0.0 click on edit icon in the block with the shoutbox, make change and press SAVE...

Fatal error: Uncaught Error: Call to a member function db_query() on null in C:\xampp\htdocs\forum\Sources\TPortalAdmin.php:3096 Stack trace: #0 C:\xampp\htdocs\forum\Sources\TPortalAdmin.php(94): do_postchecks() #1 C:\xampp\htdocs\forum\index.php(151): TPortalAdmin() #2 {main} thrown in C:\xampp\htdocs\forum\Sources\TPortalAdmin.php on line 3096

Erros in the log:

8: Undefined index: var5
 http://localhost/forum/index.php?action=tpadmin;blockedit=6;f1cc2c170af9=8e4269ef213a95d6a5b3f7626c3565c8
 C:/xampp/htdocs/forum/Themes/default/TPortalAdmin.template.php (Line 3445

8: Undefined index: var5
 http://localhost/forum/index.php?action=tpadmin;blockedit=6;f1cc2c170af9=8e4269ef213a95d6a5b3f7626c3565c8
 C:/xampp/htdocs/forum/Themes/default/TPortalAdmin.template.php (Line 3431)

8: Undefined index: var1
 http://localhost/forum/index.php?action=tpadmin;blockedit=6;f1cc2c170af9=8e4269ef213a95d6a5b3f7626c3565c8
 C:/xampp/htdocs/forum/Themes/default/TPortalAdmin.template.php (Line 3221)

8: Undefined variable: dB
 http://localhost/forum/index.php?action=tpadmin
 C:/xampp/htdocs/forum/Sources/TPortalAdmin.php (Line 3096)

**Comment by tinoest** [comment]
Fixed in #355
