### ISSUE TITLE
Undefined index errors when changing panel settings

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#354]
Changing panel setting...

8: Undefined index: var1
 http://localhost/forum/index.php?action=tpadmin;sa=panels
 C:/xampp/htdocs/forum/Sources/TPortalAdmin.php (Line 732)

Type of error: Undefined 
8: Undefined index: var2
 http://localhost/forum/index.php?action=tpadmin;sa=panels
 C:/xampp/htdocs/forum/Sources/TPortalAdmin.php (Line 733)

**Comment by Bopske** [comment]
same error when changing block overview...

http://localhost/forum/index.php?action=tpadmin;sa=blocks;overview

**Comment by tinoest** [comment]
Fixed in #355
