### ISSUE TITLE
Include an extra .css file for customer styling

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#363]
Mentioned a while ago, and it would be a valuable addition to have an extra stylesheet with Tinyportal that will allow users to add custom styling.

This stylesheet should ideally be loaded 'last' so one can override other styling elements, and it should not be deleted upon uninstall (only if delete all data is checked) and not overwritten if it already exists on install of a new version

**Comment by TPMick** [comment]
I like this idea, but how far will it go.  I mean how many parts of the portal will you be able to style by using this stylesheet?  Also would it be possible to have a admin page where you can add these overrides?

Will it also be possible to add this style sheet to custom themes individually, so you can fine tune the look for each theme?

**Comment by Bopske** [comment]
You can basically overrule ANY style with this stylesheet: TinyPortal styles but also SMF styles. 

You can edit the stylesheet in SMF admin screen like you edit any other style sheet.
And like other style sheets you can use a theme specific one. Mind you: we only install in the default theme...

Thus makes managing extra style way easier: I am for example using specific styles in articles, and to keep those styles up to date when upgrading tinyportal is always manual changes. This way the styles can be easily kept and ported when upgrading.

**Comment by lurkalot** [comment]
Thanks.  Ok so there won't be a overrides UI, it will involve getting your hands dirty and editing a file.  That's not a bad thing in this case, and will provide some control over the looks.  

There is some parts of the portal that would benefit from having that control built in to their actual admin settings, blocks articles etc, much like you did for the Shoutbox. colour settings.  You've no doubt seen my post about this in the forum.

**Comment by Bopske** [comment]
addressed by #364
