### ISSUE TITLE
2.0.0 - Changing existing article creates NEW article

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#384]
After creating an article all is fine. 
Then changing the viewing options do not get updated to the database: press save and refresh the screen changed parameters setting show correct. 

Then visit the article and no changes are found. Go back to the settings and the parameters show again unchanged...

Tried it seven times, then found that I have seven duplicate articles as a result.
![2019-04-05_183721](https://user-images.githubusercontent.com/24902644/55642847-ef889d80-57d1-11e9-8379-6e09b0b07230.jpg)
.

**Comment by tinoest** [comment]
Is this the current master or my pr with changes?

**Comment by Bopske** [comment]
Current master

**Comment by tinoest** [comment]
Thanks, I think I know what the issue is. I’ll fix it this weekend. I’m not setting a hidden value in the form correctly.

**Comment by tinoest** [comment]
Should be fixed now.

**Comment by Bopske** [comment]
Fixed
