### ISSUE TITLE
GooglePlus Throws undefinded errors 

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#394]
Upgrade of TinyPortal 2.0.0 to latest master/2.0.0 throws these errors;

    Type of error: Undefined_vars
    Error message: 8: Undefined index: tp-hidearticle-google2
    File: /var/www/html/PSMF/Themes/default/TPortalAdmin.template.php
    Line: 1334
    URL of page causing the error: https://192.168.0.65/PSMF/index.php?action=tpadmin;sa=artsettings

    Type of error: Undefined_vars
    Error message: 8: Undefined index: tp-hidearticle-google
    File: /var/www/html/PSMF/Themes/default/TPortalAdmin.template.php
    Line: 1321
    URL of page causing the error: https://192.168.0.65/PSMF/index.php?action=tpadmin;sa=artsettings

Reddit icon is also floating at the bottom of a article not inside the div.

**Comment by Bopske** [comment]
Sorry about that, fixed.
