### ISSUE TITLE
Block with single article in Frontpanel does not show the article body

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#409]
See report here: https://www.tinyportal.net/index.php?topic=36334.msg297265#msg297265

I can reproduce it in both 2.0.15 and 2.1 RC2.
What I cannot yet figure out, is what exactly is missing: I have two articles that are identical in tp_articles (all settings the same) and one is showing, and one is not...

**Comment by Bopske** [comment]
Additional info on this. It is related to the language visibility somehow. With three languages installed  the body text of article blocks are showing in one or two of the languages but not in the other.

Still only a problem on the front panel

**Comment by Bopske** [comment]
I am completely baffled and stuck on this. If you have any idea Tino I would appreciate it...

**Comment by tinoest** [comment]
What is in the dB? It might be the field isn’t long enough for three languages? 

I’ll look this evening when I’m back home.

**Comment by Bopske** [comment]
The field is not the issue. The languages are stored in the access2 field in tb_blocks.

As far as I can determine this problem only happens in the frontpanel (seems related to the fact that it has it's own code to retrieve the blocks,)
The problem is that in some situations the article body seems to simply not being retrieved, resulting in a an article block without content showing in the front panel. 

Then when I change the language it shows up for some languages but not other, when I switch off the language visibility completely it still gives the same issues: for some languages content for others not, but the comibations are different (!)
I compared tp_block table contents field by field and also the tp_articles tabel for the articles being shown and I cannot find any cause for the different results. Been digging through the code in Tportal.php, TpSubs_template.php, but I cannot put my finger on it...

Funny thing is that I have two blocks I am testing this with (HTML article block and BBC article block), and when I move these blocks to the upper panel or side panel all works as it should. Then I move them back to front panel it the problem is back...

**Comment by Bopske** [comment]
This issue is still happening for me
![2019-06-19_065105](https://user-images.githubusercontent.com/24902644/59737683-d931a000-925e-11e9-92fa-1f3aecad7168.jpg)

**Comment by Bopske** [comment]
Cannot reproduce this in TP 2.0.0 Fine to leave it behind in 164
