### ISSUE TITLE
8: Undefined index: adminhook

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#412]
2.0.0 branch

accessing the forum getting this error in the log (twice for every hit):

8: Undefined index: adminhook
 http://localhost/smf21/index.php?action=forum
C:/xampp/htdocs/smf21/Themes/default/TPsubs.template.php (Line 317)

Code;

316: | // add adminhooks
-- | --
==>317: | if(is_countable($context['TPortal']['tpmodules']['adminhook']) && count($context['TPortal']['tpmodules']['adminhook']) > 0)
318: | {
319: | foreach($context['TPortal']['tpmodules']['adminhook'] as $link)
320: | echo '<li><a href="' . $scripturl . '?'.$link['action'].'">' . $bullet5.$link['title']. '</a></li>';
321: | }
322: |  
323: | echo '
324: | </ul>';
325: | }

**Comment by tinoest** [comment]
Fixed in #421
