### ISSUE TITLE
Lost the option to deactivate modules

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#413]
Current 2.0.0 version it is no longer possible to deactivate modules. For shoutbox and tplistimages no a big issue, but tpdownloads can also no longer be disabled...

**Comment by tinoest** [comment]
We need to decide if they are part of the 'core' or a module. I'll add a setting option in the meantime.

**Comment by Bopske** [comment]
Thanks for the option, that works

**Comment by tinoest** [comment]
Fixed in #421

**Comment by Bopske** [comment]
Personally I think the whole module idea never panned out: not one extra module added ever (apart from TPlistimages) and I do not see that change.

Let’s just abandon the module setup and make it more it simple: TPShout, TPdowloads and TPlistimages are part of the package and structure of files. As long as the users have the ability to choose not to use them I do not expect anyone cares...
