### ISSUE TITLE
Fix #417 breaks PGSQL

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#418]
FIND_IN_SET isn’t supported by PGSQL, the latest commit to 2.0.0 breaks support.

**Comment by Bopske** [comment]
I see that you updated the code in TPBlocks

`	// set the location access
    $access2 = '';
    if($db_type == 'mysql') {
        $access2 = 'FIND_IN_SET(\'' . implode('\', access2) OR FIND_IN_SET(\'', $sqlarray) . '\', access2)';
    }
    else {
        foreach($sqlarray as $k => $v) {
            $access2 .= " '$v' = ANY (string_to_array(access2, ',' ) ) OR ";
        }
    }`

Can you make the same fix to Tportal, or do you want me to do it? Can't test on PGSQL myself...

**Comment by tinoest** [comment]
I’ll look at doing it, was just creating the issue so I didn’t forget.

**Comment by tinoest** [comment]
Fixed in #424
