### ISSUE TITLE
Version 200: selecting a non-frontpanel block to show on frontpage does not work

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#426]
Looks like related to the latest fixes: for blocks in panels other than the frontpanel the selecttion show on frontpage is non-functioning. 

Create a block in the side panel and only select show in frontpage does not make the block show. Setting all pages and sections does work, but only frontpage not.

**Comment by lurkalot** [comment]
I just created a bbc block, set it to only show on front page and it works as expected. This is in my left panel.

**Comment by tinoest** [comment]
Is this still a issue?

**Comment by Bopske** [comment]
Solved as far as I can see
