### ISSUE TITLE
Submit shout using enter key on active when turned off

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#432]
TP 1.6.3 - TP 1.6.4 Running on SMF 2.1 RC2.
Submit shout using enter key on active when turned off.

And turning it on results it duplicate shouts.  Hit enter and two shouts will appear.

**Comment by Bopske** [comment]
See the same thing. Seems to be related to the javascript in Tpshout.php. I have no knowledge of Javascript...

**Comment by tinoest** [comment]
I still can't replicate this...
