### ISSUE TITLE
Article smileys not showing correctly on the frontpage

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#482]
Mine is set to 1000, and it is not related to the width I think...

you can see it here: https://test2.fjr-club.nl/index.php

and here it works.. https://test2.fjr-club.nl/index.php?topic=24066

Example codes: https://www.tinyportal.net/index.php?topic=36399.msg298242#msg298242

**Comment by lurkalot** [comment]
I see the same problem.  Seems to only break the smileys if you have front page settings set to, 
"Forum-topics and articles - sorted on date"
"Promoted topics + articles - sorted on date"

If you set to one of the others such as, 
"Only forum-topics"
"Promoted topics only"

Then the smileys show up ok..
