### ISSUE TITLE
Problem with TPmodule block - shoutbox on upgraded forum

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#497]
I cannot create a shoutbox block anymore. I can still select a TP module for the block (the old fashioned way) but in the block I cannot select the Shoutbox module.

There is no module showing. 
On a clean install (after first removing the TP tables from 1.6.4) it does work...

It also throws these errors:

https://test.fjr-club.nl/index.php?action=tportal&amp;sa=editblock&amp;id=58;sescApply 8: Undefined index: tpmodules
File: /home/deb77453/domains/fjr-club.nl/public_html/test/Themes/default/TPBlockLayout.template.php
Line: 339

https://test.fjr-club.nl/index.php?action=tportal&amp;sa=editblock&amp;id=58;sescApply 2: Invalid argument supplied for foreach()
File: /home/deb77453/domains/fjr-club.nl/public_html/test/Themes/default/TPBlockLayout.template.php
Line: 339

**Comment by Bopske** [comment]
Unfortunately the fix does not solve the issue that the shoutbox cannot be selected... it solves the errors though, but I still cannot create a shoutbox block...

![2019-11-10_210237](https://user-images.githubusercontent.com/24902644/68549913-0e9d7c80-03fe-11ea-90ad-9364752809bc.jpg)

**Comment by Bopske** [comment]
Tino, I know this is difficult to troubleshoot: if you want I can send you a download of the tp tables of the upgrade forum...?

I already did som digging to find what is different, but so far no luck...

**Comment by tinoest** [comment]
> Tino, I know this is difficult to troubleshoot: if you want I can send you a download of the tp tables of the upgrade forum...?
> 
> I already did som digging to find what is different, but so far no luck...

Could you send me a copy of the tp database tables? I'll try and work out what the issue is as it's not occuring here.

**Comment by tinoest** [comment]
I've found the bug... not sure on the fix yet mind.
