### ISSUE TITLE
Extra closing div in tpshoutbox code

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#506]
@Bopske I can't find this currently but it means the center container doesn't work properly when you have a shoutbox in there, can you see if you have more luck than I finding it?

**Comment by Bopske** [comment]
How do I reproduce it? Shoutbox in the frontpanel ? What is the error? This what you mean.... http://test2.fjr-club.nl ?

**Comment by tinoest** [comment]
No, I thought I had fixed that issue.

**Comment by tinoest** [comment]
The error was there wasn't a closing </div> so the content wrapped. You seem to have a different issue.

**Comment by Bopske** [comment]
I installed yesterday's code version, so this should be the newest code...

Can you please explain exactly what settings you have made to get to the error? Otherwise I cannot troubleshoot it...

**Comment by tinoest** [comment]
![Screenshot 2019-12-21 at 14 36 40](https://user-images.githubusercontent.com/2171403/71309426-72549580-23ff-11ea-9c5b-7872d2a40b7c.png)
![Screenshot 2019-12-21 at 14 37 00](https://user-images.githubusercontent.com/2171403/71309427-72549580-23ff-11ea-9841-8bb7b308c09a.png)

I think those two screenshots show the issue, with the shoutbox enabled the other content goes to the edge of the screen, this is due to an extra "< / div >" tag in the shoutbox fetch function I think but I can't find it. 

Your issue, can you post the contents of the tp_blocks database table so I can see if its a similar issue to what I had or a new one. The latest commit merged to here should of fixed that issue.

**Comment by Bopske** [comment]
Find attached the table contents...
It is the last block (id 54)
[smf_tp_blocks.zip](https://github.com/Tinyportal/TinyPortal/files/3991523/smf_tp_blocks.zip)

**Comment by tinoest** [comment]
Thanks, I can recreate the error here. Now just to find out what is causing it.. Can you create a new shoutbox block and does that work ok?

**Comment by Bopske** [comment]
Just doing some testing: I had a TP200 install from early november. That did not have the extra div issue. The new code does..
I will see what I can find. 
By the way: that shoutbox block is one I created new and it is left empty... mind you it seems to work ok in the other panels, just not in the front panel...
