### ISSUE TITLE
My articles page does not allow non-admin to maintain articles

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#512]
Latest 200 build, both in 2.0.15 and 2.1.

As non-admin who can submit articles the 'My Articles' menu shows articles, but no descriptions.. 
![image](https://user-images.githubusercontent.com/24902644/71474394-7572cb80-27db-11ea-99a8-5600cdb80193.png)

Then clicking on the edit icon gives message: Your session timed out while posting. Please go back and try again.

![image](https://user-images.githubusercontent.com/24902644/71474409-8e7b7c80-27db-11ea-9e4a-ef95aac43cd3.png)

**Comment by Bopske** [comment]
Same happens when using the (now restored) edit link...

**Comment by tinoest** [comment]
Should be fixed in #511

**Comment by Bopske** [comment]
Part one is fixed now (the subject not showing) part 2 is still open: non-admins still get the error: Your session timed out while posting. Please go back and try again. when trying to edit any article...

**Comment by tinoest** [comment]
Should be fixed in #535 or atleast a short term fix until I sort it properly.

**Comment by Bopske** [comment]
I tested the fix and this is not what we want: My Articles now allows a non admin that does not have permissions to manage articles to  do just that: he can manage articles, update articles that are not his own and also manage article categories and PHP articles... definately not what we want...

**Comment by tinoest** [comment]
> I tested the fix and this is not what we want: My Articles now allows a non admin that does not have permissions to manage articles to do just that: he can manage articles, update articles that are not his own and also manage article categories and PHP articles... definately not what we want...

Then that might be a existing bug in the code when going to a url like I changed it to. As I have not made any other changes to allow them to do that. 

Can you test on TinyPortal 1.6.x with a url which a non admin shouldn’t be able to access?

**Comment by Bopske** [comment]
I will have a look, but may take a few days...

**Comment by tinoest** [comment]
> I will have a look, but may take a few days...

I just tested and I think it is a issue in 1.6.5 @lurkalot can you please verify.

**Comment by tinoest** [comment]
#536 Should fix this issue now.
