### ISSUE TITLE
Edit link on articles not showing anymore 

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#514]
As an admin I am supposed to see the dit link in all articles... it is not set to hidden, but in 200 the link is gone from the articles...

 
![image](https://user-images.githubusercontent.com/24902644/71477334-b376ec00-27e9-11ea-8b20-8db64f6cfe31.png)

**Comment by lurkalot** [comment]
Is this only happening in SMF 2.1 ?

**Comment by Bopske** [comment]
I believe in both 2.1 and 2.0.15

**Comment by lurkalot** [comment]
Ok so in that case only happens with an upgraded setup, because I'm running the latest 2.0.0 from the repo on a clean install of 2.0.15 and the edit link shows ok.

**Comment by Bopske** [comment]
pretty sure it is more than that, looking at the code now and I think I see what's wrong...

**Comment by tinoest** [comment]
I’ve fixed this in my PR btw, but you’re welcome to submit the fix first and I’ll merge yours in to mine.

**Comment by Bopske** [comment]
I submitted it, did not see your comment before
