### ISSUE TITLE
Members submitings articles: article has virtually no settings

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#516]
New articles submissions are missing default values, if they are approved without checking they have no title. no style and so on. In 1.6.4 these field are set by default.

We need to agree on what settings to set as defaults, because without any the articles will show poorly...

**Comment by Bopske** [comment]
Tino,

it seems to me that we should set some defaults for the settings in TPArticle.php upon submission by a user. Not sure how to go about that best... thoughts?

**Comment by tinoest** [comment]
Do we know what the defaults should be? They should be defined in that file at the start then overwritten.

**Comment by Bopske** [comment]
I have my own opinion about that, we can start with that...
I ‘ll ask a the forum fir more input . The best way would be to have a configuration page for admins to set the defaults themselves, but as long as we do nothave that this may suffice
![Image](https://i.imgur.com/Tj9zBAV.jpg)
![Image](https://i.imgur.com/n8su2zv.jpg)
![Image](https://i.imgur.com/HSWgLJr.jpg)
![Image](https://i.imgur.com/LClyuQH.jpg)

**Comment by Bopske** [comment]
If you can create the base code I am happy to add fields where needed
