### ISSUE TITLE
Avatar links in SMF2.0 not working in blocks

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#540]
After installing latest 200 build on 2.0.17 the avatars in recent topics and other blocks are not showing.

In 1.6.5 the links are showing as follows:
https://test.fjr-club.nl/eigenavatars/avatar_691_1561454547.png

In 2.0.0 the links are formatted as:
https://test.fjr-club.nl/index.php?action=dlattach;attach=15187;type=avatar

... and resulting in broken images...

**Comment by tinoest** [comment]
For me this works.

I assume the avatars are uploaded to a custom avatar directory?

**Comment by Bopske** [comment]
Yes, custom directory

**Comment by tinoest** [comment]
We had something similar before, I can't quite remember what the fix was. 

It's working ok here, but I think it might be as I am using a ip and not a url if my memory is working correctly.

**Comment by tinoest** [comment]
I've tried setting a custom directory and it all seems to work ok. Is this just in SMF2.0 or SMF2.1 also? Set it up with a URL also so it's not just a IP and still works ok.

**Comment by Bopske** [comment]
Sorry, by closing the other issue this was closed as well... unfortunately the problem is not solved....

**Comment by Bopske** [comment]
Just reproduced the exact same issue in a fresh install of 2.0.17.

Steps to reproduce:
1. Install 2.0.17 on local Xampp
2. Upload an avatar for test user
3. Check recent topics : looks fine
4. Change avatar directory to custom folder

Settings:
![2020-04-06_210711](https://user-images.githubusercontent.com/24902644/78595709-cec2b000-784a-11ea-9dcb-39ba8da00013.jpg)

5. Now upload a new avatar
6. Check recent topics : image broken

![2020-04-06_210632](https://user-images.githubusercontent.com/24902644/78595778-e7cb6100-784a-11ea-8f19-99e27ce02743.jpg)

7. Change avatar directory back to attachments folder 
8. Now upload a new avatar
7. Check recent topics : showing the new avatar correctly

![2020-04-06_210745](https://user-images.githubusercontent.com/24902644/78595884-15180f00-784b-11ea-9d91-81e628f132ec.jpg)

**Comment by tinoest** [comment]
After finally being able to replicate this it is a bug in SMF's SSI.php not TinyPortal. 

TinyPortal 2.0 uses the builtin ssi_recentTopics, 1.6.x uses its own variant of that.

**Comment by tinoest** [comment]
I take that back, it was a TinyPortal bug... now fixed.
