### ISSUE TITLE
Recent topics block in smf 2.0 empty

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#541]
Create a new recent topics block in 2.017 and the block stays 'empty'

**Comment by tinoest** [comment]
![Screenshot 2020-03-28 at 14 28 41](https://user-images.githubusercontent.com/2171403/77825347-8c89c800-7100-11ea-963d-4b71cf2e1c77.png)

This works for me. Can you tell me your settings please?

**Comment by Bopske** [comment]
![2020-03-28_180625](https://user-images.githubusercontent.com/24902644/77828940-e305ff00-711e-11ea-9c9d-88021dfcb920.jpg)

**Comment by tinoest** [comment]
I can't recreate this even on a fresh install.

**Comment by Bopske** [comment]
I will have to setup a fresh 2.0.17 install to check. This is a copy of my forum that I upgraded from 165 to 200.

**Comment by Bopske** [comment]
Hmmm, this seems to have something to do with have a relatively old test forum: recent block is not showing any content, then I create one new posting, and all of a sudden the block shows 10 recent topics !
Deleting the message and the block is empty again...

Need to check the SMF SSI.php code

**Comment by Bopske** [comment]
I am closing this. Has nothing to do with TinyPortal but with  ssi_recentTopics in SMF
Just checked ssi_examples.php and it does the exact same thing...
