### ISSUE TITLE
Setting a block to show on frontpage only does not work

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#542]
Setting a block to only show on frontpage: block does not show. Setting it to show everywhere and it sgows also on the frontpage.

Same applies to article pages: setting it to show on an article page and the block does not show for the article. Same for categories.

SMF: 2.0.17
Upgraded forum
TP: 200

**Comment by Bopske** [comment]
Just checked it on SMF 2.1: same result

**Comment by Bopske** [comment]
Some more details: setting the block to show on frontpage ONLY works. 

The block seems to disappear if I also select the block to show on any article of article category page. Removing the article or category selection for the block makes it appear on the frontpage again...

**Comment by tinoest** [comment]
> Some more details: setting the block to show on frontpage ONLY works.
> 
> The block seems to disappear if I also select the block to show on any article of article category page. Removing the article or category selection for the block makes it appear on the frontpage again...

Sorry whats the article of article category page?

**Comment by Bopske** [comment]
Problem is both on article page and category pages

**Comment by tinoest** [comment]
The bit where you say "The block seems to disappear if I also select the block to show on any article of article category page. Removing the article or category selection for the block makes it appear on the frontpage again..." I don't understand what you mean.

**Comment by Bopske** [comment]
I meant so say when a block is set on any article page or on a article category page

**Comment by Bopske** [comment]
I have a calendar block: If I set to "Display on all pages and sections" the block is showing all throughout te forum as well as on any article page or category page. That's OK

![2020-03-28_175446](https://user-images.githubusercontent.com/24902644/77828793-efd62300-711d-11ea-9845-e7eb98ea815a.jpg)
![2020-03-28_175513](https://user-images.githubusercontent.com/24902644/77828794-f1075000-711d-11ea-8fbb-e2d0c00f5f1e.jpg)

Then I change the block settings: remove the "Display on all pages and sections" and instead select all Article Categories (or All pages for that matter). Normally the block will now only show on the selected article pages or category pages. Instead it is not showing anywhere...

![2020-03-28_175549](https://user-images.githubusercontent.com/24902644/77828873-68d57a80-711e-11ea-9ab5-441ee3ef0fd8.jpg)

![2020-03-28_175857](https://user-images.githubusercontent.com/24902644/77828797-f2387d00-711d-11ea-9e9b-8f4f7deb8c25.jpg)

**Comment by tinoest** [comment]
Wen you don't toggle all and choose just one article does it work ok?

**Comment by Bopske** [comment]
Updated code from #544 fixes the issue

**Comment by Bopske** [comment]
This has been fixed
