### ISSUE TITLE
Language specific block titles are missing

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#553]
Cannot maintain language specific block titles...\

![2020-04-11_214342](https://user-images.githubusercontent.com/24902644/79055167-13838800-7c4b-11ea-8c56-c50aac844f3d.jpg)

**Comment by tinoest** [comment]
Is that the image you wanted to upload @Bopske? I’m not sure what it’s telling me if it is.

**Comment by Bopske** [comment]
Sorry, indeed, wrong image attached... replaced with correct one

**Comment by tinoest** [comment]
Do you have any other languages installed?

**Comment by Bopske** [comment]
Ouch, good call! 

Sorry about that: in this one forum it's only English... missed that move along, nothing to see here...
