### ISSUE TITLE
Ordering block behaves erraticly

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#554]
Sorting blocks in the blocks admin: when moving a block up or down in the list sometimes block is pushed all the way down instead of 1 position.

Clicking the up arrows is supposed to move the block up 1 postion: instead it moves to top.
Not all the time though...

![2020-04-11_215014](https://user-images.githubusercontent.com/24902644/79053589-d0231c80-7c3e-11ea-96de-955ca1b8a72f.jpg)
![2020-04-11_215024](https://user-images.githubusercontent.com/24902644/79053590-d0bbb300-7c3e-11ea-9744-9dedbfaac558.jpg)

**Comment by lurkalot** [comment]
I will have to test this actually.  I have a habit of just typing in the position numbers to change block position, and forget those up/down buttons are there.   I know in the past, a long time ago clicking the arrow would work first time, but after that they would stop working,.  I've not seen them jump position in that way before though.

**Comment by tinoest** [comment]
I can recreate this in 1.6.5 so I guess it's not a new bug? 

I'll look in to it.

**Comment by Bopske** [comment]
Could be, did not notice this before...
