### ISSUE TITLE
Member with manage articles permission does not get 'Sections' Bar in articles 

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#577]
A regular member (non admin)  with manage articles permissions cannot create articles and categories because the sections bar does not show. It does for admins...

See below..

Admin
![2020-05-07_212726](https://user-images.githubusercontent.com/24902644/81339475-8c40fd00-90ae-11ea-8a56-3c8d1e8c55fb.jpg)

Member with manage articles permission
![2020-05-07_212712](https://user-images.githubusercontent.com/24902644/81339494-92cf7480-90ae-11ea-8367-192be8960634.jpg)

**Comment by tinoest** [comment]
That's this change to remove non admin from being able to access this, I'll have to add a check to see if they can manage an article then enable it again. 

https://github.com/Tinyportal/TinyPortal/pull/536/files#diff-df7cc9e2610fc75bd41e271e6a187b9aR148
