### ISSUE TITLE
Issues with setting "Path where TinyPortal images are uploaded to on your server"

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#616]
Did some tests, not sure how to fix so logging it here.

1. After changing the path from default  the image upload function does not work anymore. No errors, but images are not uploaded

2. The quicklist only shows images in the default folder due to this code in subs.php:
img src="'.$boardurl.'/tp-files/tp-images/', substr($im,6) , '"  alt="" /
Should be updated to use the variable

3. TPlistimages does not use the setting at all: all hardcoded...
Can be changed, but then it is only possible to manage the NEW files... hmmm

**Comment by Bopske** [comment]
For 2.0.0 I have disable the admin settings. This feature may be finished in 2.1.0

**Comment by Bopske** [comment]
Continuing the open question here about the boardurl links...

I have moved the tp-images folder back and updated the setting to the old standard folder /tp-images

The variable $context['TPortal']['image_upload_path'] is used where it was already implemented by you and I also updated some other locations (tplistimages to start). The download manager needs to be updated still, but to do it completely we also need a variable for dealing with $boardurl instead of $boarddir.

Not sure if there is a simple trick to add a boardurl variable to $context that is derived from boarddir?
Do you have a tip for me?

---


Good example is line 121:
$imageUrl   = $boardurl.'/tp-images/thumbs/'.$im;

By the way: the same applies to the variable for the downloads: $context['TPortal']['download_upload_path']
There are also images placed in the sub-folder here, so when moving the downloads folder these images also need to be redirected, so another boardurl variable there..

For example; TPdlmanager.php

Line 2239.
$icon = $boardurl.'/tp-downloads/icons/'.$_POST['newdladmin_icon'];

**Comment by tinoest** [comment]
Partially fixed in #787

**Comment by tinoest** [comment]
Closed in #788
