### ISSUE TITLE
User with edit own article permissions can edit articles from other users

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#629]
As the title says...

**Comment by tinoest** [comment]
Is this in 1.6 also?

**Comment by Bopske** [comment]
pretty sure it is not, since in 1.6 the whole user that edits his own articles in a separate template..

**Comment by tinoest** [comment]
Ok, I’ll just add the check to make sure it’s your own article if that’s set for 2.0

**Comment by Bopske** [comment]
Note that currently the user can also access the other 'article' subactions that he should not access: 
action=tpadmin;sa=categories 
action=tpadmin;sa=artsettings
action=tpadmin;sa=articons
action=tpadmin;sa=articles
action=tpadmin;sa=addarticle_import
