### ISSUE TITLE
Frontpage "Only forum-topics" showing topics multiple times with multiple attachements

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#631]
Frontpage issue:

When using the layout option "articles + icons" and 'Only forum-topics',  topics are listed multiple times: it includes the topic for each attachment in the first topic, where it should only use the FIRST attachment of the topic...
![2020-06-13_214306](https://user-images.githubusercontent.com/24902644/84577747-5be03300-adbf-11ea-9a1b-ed1ffa4afd3e.jpg)

**Comment by tinoest** [comment]
This is also a bug in 1.6.x... as I have not changed that logic.

**Comment by Bopske** [comment]
You may be right. I am personally not using the layout, but with the new release testing 'everything'
