### ISSUE TITLE
Function deleteComment in Base.php should update total comments per article

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#640]
The function  insertComment updates the total comments field for the article after inserting the new comment. The function to delete comments shoudl actually update the total comments if a comment is deleted.

Now the comment counter is misstating the actual number of comments...

This function should be extended to decrease the number of comments for the article:

    protected function deleteComment($id, $type) {{{
        
        $this->dB->db_query('', '
			DELETE FROM {db_prefix}tp_comments
			WHERE id = {int:id}
            AND item_type = {string:type}',
			array(
				'id'    => $id,
                'type'  => $type
			)
		);

**Comment by tinoest** [comment]
It should be done outside of this function as I was going to extend it for download comments etc. 

I’ll look at it changing those.
