### ISSUE TITLE
Dlsubmitsuccess missing subaction

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#648]
User that submits a download gets an error message: this line needs to be adapted to use subaction;
TPdlmanager.php
Line 404: 				redirectexit('action=tportal;sub=dlsubmitsuccess');

**Comment by tinoest** [comment]
Is that not just adding sa=download; like the other places?

**Comment by Bopske** [comment]
No, tried that already

**Comment by tinoest** [comment]
Line 47 and 51 in tpdownload needs to be switched and the sa=download added

**Comment by Bopske** [comment]
Fixed by #649 649
