### ISSUE TITLE
Token verification failed 

### ISSUE THREAD

**Issue by lurkalot** [Tinyportal/TinyPortal#679]
Both TP 1.6.7 and TP 2.0.0 running on the latest repo version of SMF 2.1

Logging in via the TinyPortal User block results in the following error on page.
"Token verification failed. Please go back and try again"

No errors in log. 

Support topic for reference, https://www.tinyportal.net/index.php?topic=36519.0

**Comment by Bopske** [comment]
Fixed by #681
