### ISSUE TITLE
Image upload path is not working

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#698]
Cannot upload images and the TPlistimages does not work either.

Getting these errors: \
https://www.fjr-club.nl/index.php?action=tpadmin;listimage=list
2: opendir(/home/deb77453/domains/fjr-club.nl/public_html/tp-files/tp-images/thumbs): failed to open dir: No such file or directory
Bestand: /home/deb77453/domains/fjr-club.nl/public_html/Sources/TPListImages.php
Regel: 174

**Comment by tinoest** [comment]
tp-files shouldn’t in the path

**Comment by Bopske** [comment]
Yep, I took it out, but no change...
and the directory DOES exit...

Type of error: General
2: opendir(/home/deb77453/domains/fjr-club.nl/public_html/test2/tp-images/
thumbs): failed to open dir: No such file or directory
https://test2.fjr-club.nl/index.php?action=tpadmin;sa=editarticle;article=92
/home/deb77453/domains/fjr-club.nl/public_html/test2/Sources/TPSubs.php (Line 892)

**Comment by tinoest** [comment]
If it does exist and you’re getting that then permissions?

**Comment by Bopske** [comment]
all set to 755

**Comment by tinoest** [comment]
I’ll try it tomorrow, although I have a feeling it will work for me. It’s maybe catching something and you need to restart Apache or call clearstatcache in php

**Comment by Bopske** [comment]
I just deleted the tables and re-installed clean, and now it does work.

But on the second site on the domain it does not...
