### ISSUE TITLE
Block upshrink doesn't work

### ISSUE THREAD

**Issue by Oldiesmann** [Tinyportal/TinyPortal#699]
A user on my seniors site pointed out that blocks won't stay collapsed.

After doing some digging I found that the upshrink URL isn't working. Chrome's Developer Tools console shows the "GET" request returning an HTTP 500 status code (possibly because of the Optimus Brave mod?), and going to the URL directly gives you an error stating "No subaction found in URL".

**Comment by Bopske** [comment]
What version of TP and what version of SMF are you using? Link to the site where it happens?

**Comment by Oldiesmann** [comment]
TP 2.0.0 RC1 (GitHub revision as of August 15th) and SMF 2.1 RC2 (newer than official RC2 release but way behind where they're currently at on GitHub - waiting on the privacy policy stuff to get pushed through before I upgrade).

The site this happens at is https://www.seniorsandfriends.org
