### ISSUE TITLE
Can't install TinyPortal with STRICT_TRANS_TABLES enabled

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#71]
The SQL needs to be refactored to allow it to run under stricter SQL rules.

**Comment by tinoest** [comment]
Need to add defaults to all text fields primarily to sort this one now. Most of the others are sorted. @Bopske  can you look into this?

**Comment by Bopske** [comment]
I can check it out, but will take a few days before I have time again...

How can I test this? What code in the install do I need to take out to test the install under strict rules?

**Comment by tinoest** [comment]
Remove this for SMF 2.1 forum_version;

    // Remove the ONLY_FULL_GROUP_BY and STRICT_TRANS_TABLES keep all the other sql_mode settings
    if(strpos($forum_version, '2.1') !== false) {
        global $smcFunc;
        $modSettings['disableQueryCheck'] = true;
        $sqlMode  = $smcFunc['db_query']('' ,
                'SELECT @@sql_mode AS SQL_MODE;'
                );
        if($smcFunc['db_num_rows']($sqlMode) === 1) {
            $sqlModeResult = $smcFunc['db_fetch_assoc']($sqlMode)['SQL_MODE'];
            if(strpos($sqlModeResult, ',') !== false) {
                $sqlModeResults = explode(',', $sqlModeResult);
                foreach($sqlModeResults as $key => $value) {
                    if(in_array($value, array('ONLY_FULL_GROUP_BY', 'STRICT_TRANS_TABLES'))) {
                        unset($sqlModeResults[$key]);
                    }
                }
            }
            $smcFunc['db_query']('',
                    'SET SESSION sql_mode = \''.implode(',', $sqlModeResults).'\';'
                    );
        }
        $smcFunc['db_free_result']($sqlMode);
        $modSettings['disableQueryCheck'] = false;
    } 

Should bring up the issue.

**Comment by Bopske** [comment]
Ok. Does this have a relation to the issue reported on SMF forum?

**Comment by tinoest** [comment]
It does, or atleast I think it does.
