### ISSUE TITLE
Admin Panel is broken - Left Panel now goes along the top of the page

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#718]
![Screenshot 2020-09-26 at 14 49 10](https://user-images.githubusercontent.com/2171403/94342228-86b96480-0007-11eb-96d8-c3f637a4d77d.png)

Latest download and merge of TinyPortal as of today results in the above in both SMF 2.0 and SMF 2.1

**Comment by Bopske** [comment]
Did you refresh?

**Comment by Bopske** [comment]
Probably stupid to ask, but I all shows fine for me....

**Comment by tinoest** [comment]
I have, I also forced a refresh. 

It doesn't do it in Firefox or Chrome. Does in Safari. It's not enough for me to worry about, the front page is also ok in Firefox and Chrome.

**Comment by Bopske** [comment]
I will look into it. Not a regular Safari user, must be some css that safari does not support...

**Comment by Bopske** [comment]
Tino, I just checked it both on an Ipad and on an Imac using Safari, deleted the Cache just to be sure: I cannot reproduce what you are seeing. The admin screen is working fine for me..


![image](https://user-images.githubusercontent.com/24902644/94345126-179e3900-0024-11eb-8e43-6e179921b90a.png)

**Comment by tinoest** [comment]
I think just leave it for now. I can’t reproduce on any other browser and I guess safari is having a funny five

**Comment by Bopske** [comment]
will reopen if it surfaces...
