### ISSUE TITLE
Upshrink leading to "Unable to load the 'main' template" errors for guests

### ISSUE THREAD

**Issue by Oldiesmann** [Tinyportal/TinyPortal#733]
Seeing this a lot...

Unable to load the 'main' template
.../index.php?action=tportal;sa=upshrink;id=

This only seems to be happening for guests and no id is ever included in the URL if that helps at all.

**Comment by tinoest** [comment]
No ID being included means the check is never run for upshrink. 

I don’t see how it’s not included atm unless people are calling that url independently currently.

**Comment by tinoest** [comment]
Do you have any further information to help me track this down? Maybe the access logs around the time the issue occurs.

**Comment by Bopske** [comment]
Looks like some bot accessing a made-up link...
