### ISSUE TITLE
Type of error: Undefined 8: Undefined index: b

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#746]
Latest version gives constant errors on shoutbox refresh...

Type of error: Undefined
 8: Undefined index: b
 https://test2.fjr-club.nl/index.php?action=tpshout;shout=fetch
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Sources/TPShout.php (Line 50)

**Comment by tinoest** [comment]
TPupdateShouts in the TPShoutTemplate needs the block_id adding to it. 

Although I can't find which one does, are you sure you have the latest js file and template?

**Comment by Bopske** [comment]
Just installed the latest development branche on 2.1 RC3, so all files are up to date

**Comment by tinoest** [comment]
> Just installed the latest development branche on 2.1 RC3, so all files are up to date

Currently I can’t replicate, no changes are showing between my installed and what’s in GitHub. Have you cached the JS file?

**Comment by Bopske** [comment]
Cleared all cache, and de error returns with every refresh interval

**Comment by Bopske** [comment]
I found the cause: I have THREE shoutbox blocks on my old forum, and I forgot to update one block to the new logic. So the error was coming from the last (unconverted) shoutbox block. Once I updated that top the new setting errors went away

**Comment by Bopske** [comment]
Still happening...

Noticed this filter statement in TPShout.php. The b does not make sense to me there?

		$shout      = str_ireplace(array("<br />","<br>","<br/>"), "\r\n", $shout);

        $block_id   = TPUtil::filter('b', 'post', 'int');
        if(empty($block_id)) {
            $block_id = 0;
        }

**Comment by tinoest** [comment]
Fixed in #758
