### ISSUE TITLE
Can no longer disable shoutbox refresh

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#751]
After setting the refresh for the shoutbox to anything other than 0 you get an error saying 0 is not allowed when you try and set it back.

**Comment by tinoest** [comment]
Also an issue on 2.0.0

**Comment by Bopske** [comment]
Fixed for 2.0.1 can we create a new release for 2.0.1? I never created a release, don’t my trying that...

**Comment by tinoest** [comment]
@Bopske pushed the fix to the tag release

// Switch to local master branch
git checkout master

// Fetch the lastest master
git fetch master

// Merge the lastest upstream master into local
git merge master/master

// Delete the local tag
git tag -d v2.0.1

// Create a new local tag
git tag v2.0.1

// Delete the master remote tag
git push master :v2.0.1

// Push the changes to the new master remote tag
git push master v2.0.1

**Comment by Bopske** [comment]
Are the instructions for me or did you do it already?

**Comment by tinoest** [comment]
> Are the instructions for me or did you do it already?

It has been done, the instructions are just for your reference.

**Comment by Bopske** [comment]
Thanx
