### ISSUE TITLE
Shoutbox history button does not take into account shoutbox ID

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#762]

**Comment by tinoest** [comment]
What do you expect it to look like?

**Comment by Bopske** [comment]
Well, the link takes you to the general page... /index.php?action=tpshout;shout=show50

Thing is that it is not a block anymore, but a generic shoutbox display. Since it is not a block, it does not have a shoutbox layout setting. I am a bit doubtful about how to go about it. 

I think we have two options:

1. Use a generic layout mode. We can just put the general shoutbox layout option back and it would work
2. Somehow adopt the block layout from the block used to go to the page.. but it might become a bit messy using different layouts...

What do you think?

**Comment by tinoest** [comment]
If we broke the link, then restore that so it looks like it used to. I don't really want to spend much time on the additional things outside of the 'core' for TinyPortal going forward.

**Comment by Bopske** [comment]
i'll have a look

**Comment by Bopske** [comment]
Fixed
