### ISSUE TITLE
Error messages when regular users write articles

### ISSUE THREAD

**Issue by Hatshepsut71** [Tinyportal/TinyPortal#768]
Hello,
I am using Tinyportal 2.0 and 2.0.1, on two SMF 2.1 RC3 forums.
Regular users have permisions to write either BBC and HTML articles, but if choosing that, they get error messages:

Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 67
Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 77
Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 116
Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 117
Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 132
Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 135
Notice: Trying to access array offset on value of type bool in /home/bulataka/public_html/test/Themes/default/TParticle.template.php on line 143

I will attach a screenshot from one of forums, with Tinyportal 2.0.1:
![2020-11-28](https://user-images.githubusercontent.com/68983397/100495694-aa5b7100-3156-11eb-894d-fef9b14ab44a.png)

I get the same error messages with Tinyportal 2.0

Submission of articles is possible, but they are not assigned to a category.

**Comment by Hatshepsut71** [comment]
Forum version: SMF 2.1 RC3 (more detailed)
Current SMF version: SMF 2.1 RC3
GD version: bundled (2.1.0 compatible)
ImageMagick version: 6.9.10-68 Q16 x86_64 2020-04-13 https://imagemagick.org (Imagick 3.4.4)
MySQL engine: MariaDB
MySQL version: 10.3.27-MariaDB-log
PHP: 7.4.11 (more detailed)
Server version: Apache

**Comment by Bopske** [comment]
Articles submitted by members are not assigned to a category by default. That's standard: a user with 'Manage articles' permission will need to assign to the category.

as for the message: "Notice: Trying to access array offset on value of type bool in" I am seeing the same errors in a test forum with TP 2.0.1 and PHP 7.4.12... in my case they only show in the error log though..

**Comment by tinoest** [comment]
> as for the message: "Notice: Trying to access array offset on value of type bool in" I am seeing the same errors in a test forum with TP 2.0.1 and PHP 7.4.12... in my case they only show in the error log though..

Display errors is set to on in @Hatshepsut71 system I would guess, you can do the same if you change the php.ini or use this function.

https://www.php.net/manual/en/function.ini-set.php

**Comment by tinoest** [comment]
Changing this line https://github.com/Tinyportal/TinyPortal/blob/3df0204200b1cd27203fece6af37c49b127d59f8/Themes/default/TParticle.template.php#L32

To the following will solve the issue, i'm not sure on the side effects yet, there shouldn't be any as they are just defaults. 

`$mg` = array( 'off' => 1, 'id' => '', 'body' => '', 'subject' => '', 'shortname' => '', 'useintro' => 0, 'date' => time(), 'intro' => '');
