### ISSUE TITLE
Users with hidden online status are not shown in "Top Posters" block

### ISSUE THREAD

**Issue by Hatshepsut71** [Tinyportal/TinyPortal#775]
Hello,
I use Tinyportal 2.0 with SMF 2.1 RC3 forum.
I have noticed that users with hidden online status are not shown into "Top Posters" block.
One of members (with hidden status) has 402 posts, but their name is not shown in the "Top Posters", in the list is shown another user with 264 posts only.

Link to the forum:
https://bg-nacionalisti.org/BNF/index.php?action=forum

**Comment by Bopske** [comment]
Can you please report this in the support page at tinyportal.net? 

This may be intentional ...

**Comment by tinoest** [comment]
Looking at the code it is intended that way. 

I can understand why as if you’re hidden you don’t want people to easily see your details by nature.

**Comment by Bopske** [comment]
So, not an issue. Feel free to request a change in the support portal though...
