### ISSUE TITLE
Double shoutboxes on one page: shoutbox layout setting

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#794]
If I set two shoutbox to show on the same page, the block layout setting is not respected. All shoutboxes use the same layout, even when a different layout is selected...

**Comment by tinoest** [comment]
Do they have the same ID’s? 

This didn’t used to happen when I first did the conversion.

**Comment by tinoest** [comment]
It's due to this line; https://github.com/Tinyportal/TinyPortal/blob/349869b257e3ef4ef9a12f45dfaca3387a56df5d/Sources/TPShout.php#L787

I don't know where var1 is set but it needs to be different each time.

**Comment by tinoest** [comment]
This sorts it https://github.com/Tinyportal/TinyPortal/pull/793/commits/a6c514aa9619089b2f857db3c397522d4b3ccabe

**Comment by Bopske** [comment]
Thanks, that works initially, but when the Ajax refresh kicks in both shoutboxes are getting the same layout again...

**Comment by tinoest** [comment]
Weird it should pass it through. Do you have a Ajax refresh on them both?

**Comment by tinoest** [comment]
It appears to work fine for me with the latest branch. So not sure where your's is breaking.

**Comment by tinoest** [comment]
Is this still breaking with a clean install of the latest branch?

**Comment by Bopske** [comment]
Just installed the latest on a clean install of 2.0.17. Seems OK there.

**Comment by tinoest** [comment]
Can this be closed?

**Comment by Bopske** [comment]
Just checked it on a new install of 2.1.0 and it works there, so I am closing this
