### ISSUE TITLE
Block permissions non functional

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#796]
Doing some tests with shoutbox blocks for different user groups and I am finding the block setting for "Choose the membergroups that will able to see this block." does not work anymore: every user now sees all blocks, even blocks that are not set as accessible for them

**Comment by Bopske** [comment]
Same applies to this setting: Choose the membergroups that can edit this block.

**Comment by tinoest** [comment]
Try #797 

I didn't make any changes to the edit block logic to my knowledge.

**Comment by tinoest** [comment]
I can't get the editblock per user permissions to work on any of them before 2.1.0 so you are going to have to tell me how that used to work. I also can't see in the code how it did work as it populates can_edit then does nothing with it.

**Comment by Bopske** [comment]
I cannot tell you: it has always worked and I did not change anything to it either... 

Pretty sure it works in 2.0.0

**Comment by Bopske** [comment]
Just check 2.0.0 and I can confirm it works there

**Comment by tinoest** [comment]
I just checked 2.0.0 and the can edit doesn’t work in there unless I enable blocks in permissions then I can’t disable it. 

Also the logic to check permissions in 1.6.6 would not allow you edit it either unless you had tp_block set as a permission.

**Comment by Bopske** [comment]
Sorry, I only checked the SEE blocks: that works in 2.0.0, need to check the edit blocks too, but not at a pc anymore . Tbh the SEE blocks issue is more important imo because users will now see blocks that their membergroup has no permission for...

**Comment by tinoest** [comment]
> Sorry, I only checked the SEE blocks: that works in 2.0.0, need to check the edit blocks too, but not at a pc anymore . Tbh the SEE blocks issue is more important imo because users will now see blocks that their membergroup has no permission for...

As I said that’s fixed in #797. Probably why you should only have one issue per issue...

**Comment by tinoest** [comment]
> Sorry, I only checked the SEE blocks: that works in 2.0.0, need to check the edit blocks too, but not at a pc anymore . Tbh the SEE blocks issue is more important imo because users will now see blocks that their membergroup has no permission for...

What do you want to do about the edit options? I don't think it's been functional for a while.

**Comment by Bopske** [comment]
I think we should include Mick in the discussion. In the current form I am not sure if this function is useful, because the edit blocks permission grants access anyway. 

Looking at it now, it seems to me the block setting is not very useful, and since no one complained, I doubt that it will be missed . I would vote to remove it...

**Comment by Bopske** [comment]
Let’s remove this.

**Comment by Bopske** [comment]
Closed with https://github.com/Tinyportal/TinyPortal/pull/804
