### ISSUE TITLE
Error 8: Use of undefined constant TP_SMF21 - assumed 'TP_SMF21'

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#798]
Just installed 2.1.0 on a clean 2.0.17 install. Mind you: it is running on php7.1, but I don't think that is the reason.
Now getting these errors...

http://localhost/smf/index.php?action=tpadmin
8: Use of undefined constant TP_SMF21 - assumed 'TP_SMF21'
File: C:/xampp/htdocs/smf/TinyPortal/Integrate.php
Line: 126

**Comment by tinoest** [comment]
You should get the same error in 2.0.0 then...

**Comment by Bopske** [comment]
No, if that was the case I would have logged it before...

**Comment by tinoest** [comment]
> No, if that was the case I would have logged it before...

Well that code has been there since 2.0.0....

**Comment by Bopske** [comment]
then something else must have changed... perhaps it's my test install, I'll delete it and start again...

**Comment by tinoest** [comment]
> then something else must have changed... perhaps it's my test install, I'll delete it and start again...

Can you recreate this?

**Comment by Bopske** [comment]
Have not gotten around to testing it.

**Comment by Bopske** [comment]
Just installed clean 2.0.18 ad installed 2.1.0 on it: no problems...
