### ISSUE TITLE
Strange behaviour shoutbox with multiple shoutboxes on the same page

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#799]
Strange behaviour shoutbox with multiple shoutboxes on the same page

This is on a clean SMF 2.1 RC3 install

How to reproduce:
1. Install TP 2.1.0 'clean'
2. Place a shout message in the shoutbox (just for fun)
3. Create a new shoutbox in the Upper panel
	Choose the Shoutbox ID for this block: 1
	Shoutbox layout: 2
	Choose where the block should appear: Board Index
4. Now checkout the Board Index

Both shoutboxes are showing, but both are showing the content AND the layout of the default shout box
> wrong

Now change the Shoutbox id for the second shoutbox to 2 and check the board index > no change!
Both shoutboxes keep showing the same content and layout while on the board index.

Now change the first shoutbox to only display on the frontpage:
check the frontpage (shoutbox 1) and board index (shoutbox 2) and both are showing the correct content and layout now...

Changing the shoutbox ID to an ID that does not have any shouts in, brings back the issue. It seems that if a block has a shoutbox ID for which no shouts are made, the box is showing the shouts for shoutbox ID '0' if there is another shoutbox block on the page?

**Comment by tinoest** [comment]
Does it do the same if the default is 1? If not we’ll just change the logic so that 0 isn’t allowed.

**Comment by Bopske** [comment]
Thing is: I set it to 0 as default so upgrades will show the old posts.

I li find it strange that both layout and Id is screwed by this ...

**Comment by tinoest** [comment]
It’d guess it’s an empty check or something similar. Passing 0 around isn’t ideal really. 0 should really be nothing or no setting.

**Comment by Bopske** [comment]
Ok, so I updated the install code to migrate the old shouts to default shoutbox ID "1".
https://github.com/Tinyportal/TinyPortal/pull/800

The install works fine, the shoutboxes work OK. There is still one issue though:
when I create an extra shoutbox for a new shoutbox ID and I put it on the same page as an existing shoutbox block, the first page load will use the layout and show the shouts from the other (older) shoutbox. 

Then when de Ajax refresh kicks in, the correct layout is adopted and the other shouts are no longer showing.

Problem goes away as soon as the first shout is created for the new shoutbox: then the initial load for a page is correct...

**Comment by tinoest** [comment]
Then it's something to do with the logic on the first page load...
