### ISSUE TITLE
Shortenstring logic in Downloads is adding extra breaks around paragraph tags

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#810]
My changes to the downloads to incorporate the shortingstring routine still has a flaw:
When using HTML the shortenstring inserts extra breaks...

As it turns out every <p > and </p > tag seems to get an extra <br > resulting in the extra spacing.

See:
https://www.tinyportal.net/index.php?topic=36590.msg300667#msg300667

**Comment by tinoest** [comment]
https://github.com/Tinyportal/ElkTP/pull/19/commits/5b60746de3043e464bcf1a87c802820da20bc2fa fixes the issue

**Comment by Bopske** [comment]
I’ll check it out.. tnx

**Comment by Bopske** [comment]
Hmm, it solves the extra linebreaks, but now I find cases where the break is in the middle of the {BR}, resulting in leftovers showing to the user...

![2021-01-02_195142](https://user-images.githubusercontent.com/24902644/103464473-33586000-4d34-11eb-9757-2f535801f7b5.png)

I have experimented with different values instead of {BR} but nothing that is 100%... is there a way to make the shortenstring cut just before the {BR} tag?

**Comment by tinoest** [comment]
We're making this far to complex for what it is now. I'll see but some other use case where it breaks will appear.

**Comment by tinoest** [comment]
Just remove all the str_ireplace for the < br > is probably best, if it break's its the contents fault and not the shortenString logic. People shouldn't put rubbish in there.

**Comment by Bopske** [comment]
I assume you mean take this entire line out, right?

$string     = str_ireplace(array("<br />","<br>","<br/>","<br />","&lt;br /&gt;","&lt;br/&gt;","&lt;br&gt;"), BR, $string);

**Comment by tinoest** [comment]
Along with the conversion back, it breaks other things doing that mind, but we're just chasing our tails here and if the input is rubbish we might as well output rubbish, rather than tidying it up.

**Comment by Bopske** [comment]
Problem is that the input comes from mutiple places and in different froms: it is not the users fault that the data seems 'rubbish'
There really is not much the user or admins can do to prevent this. 

So just saying, garbish in garbish out does not really help. I do have similar feeling though...

**Comment by tinoest** [comment]
We either have to accept there are some use cases it will break, or we don't try and sanitise the data. 

Can you provide me with a string to break it btw like you did for the {br, I can see how it would occur but no matter what I put will break it.

**Comment by tinoest** [comment]
You can try this fix https://github.com/tinoest/ElkTinyPortal/commit/acf5f165be45337832dbf3cd6b2855fa8587eded which seems to work ok on Elkarte. It refactors the logic a bit but leaves the fix in place.

**Comment by Bopske** [comment]
I'll have another look.

Find below the full string that breaks @ 300 characters...

[example.txt](https://github.com/Tinyportal/TinyPortal/files/5760792/example.txt)

**Comment by Bopske** [comment]
Seems to work, but I need to check more cases... what also puzzles me is that strings are still breaking in the middle of words: I was under the impression that it should break at a space...?

![2021-01-02_211038](https://user-images.githubusercontent.com/24902644/103465769-137a6980-4d3f-11eb-86c4-4ab51d45afdf.png)

**Comment by tinoest** [comment]
It used to, but with all the use cases and changes that’s no longer the case. I’ll try and work out where that got lost. bbcode, seems to work ok.

**Comment by tinoest** [comment]
https://github.com/Tinyportal/ElkTP/pull/20 should wrap all the fixes up now.

**Comment by Bopske** [comment]
Looks Ok, lets merge it.

**Comment by Bopske** [comment]
Ok now
