### ISSUE TITLE
Visit to non-existing page gives multiple errors

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#812]
When visiting a page that does not exist, multiple errors are logged in the forum:

Type of error: General
2: in_array() expects parameter 2 to be array, null given
https://test2.fjr-club.nl/index.php?page=something
/home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 146) 

Type of error: Undefined
8: Undefined index: tp_panels
 https://test2.fjr-club.nl/index.php?page=something
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 146)

Type of error: General
2: in_array() expects parameter 2 to be array, null given
 https://test2.fjr-club.nl/index.php?page=something
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 132)

Type of error: Undefined
8: Undefined index: tp_panels
 https://test2.fjr-club.nl/index.php?page=something
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 132)

Type of error: General
2: in_array() expects parameter 2 to be array, null given
 https://test2.fjr-club.nl/index.php?page=something
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 117)

 Type of error: Undefined
8: Undefined index: tp_panels
 https://test2.fjr-club.nl/index.php?page=something
 /home/deb77453/domains/fjr-club.nl/public_html/test2/Themes/default/TPBlockLayout.template.php (Line 117)

**Comment by tinoest** [comment]
Hasn’t this been an issue since day dot? 

What page are you referring to specifically?

**Comment by Bopske** [comment]
This is new to me. Does it in 2.1.0 
The page is any non-existing article name...
In 2.0.0 and 2.0.1 no errors...

This article exists: https://test2.fjr-club.nl/index.php?page=Welkom
No errors there

This does not: https://test2.fjr-club.nl/index.php?page=something
Errors...

**Comment by tinoest** [comment]
I have added tp_hidebars when an error occurs, it was due to me moving the block logic loading position. I don't think you should see the panels on an error myself so that to me is the nicer error message.
