### ISSUE TITLE
TPDownloads Upload Section shows blocks

### ISSUE THREAD

**Issue by tinoest** [Tinyportal/TinyPortal#814]
The upload page/section in the download area has the blocks showing, this isn’t shown on category listings or others and they should be hidden.

**Comment by Bopske** [comment]
Is this new in 2.1.0?
Need to check it...

**Comment by tinoest** [comment]
> Is this new in 2.1.0?
> Need to check it...

I don’t think so, however I’m not sure it’s actually a bug. More a preference.

**Comment by Bopske** [comment]
Closed, since it is a taste issue...
