### ISSUE TITLE
unix file endings

### ISSUE THREAD

**Issue by Underdog-01** [Tinyportal/TinyPortal#823]
Some files have Windows EOL's while others have Unix EOL's.

Every file should have Unix EOL's.
All developers should have their editor set to use Unix EOL's as default and the existing files need to be edited to change the EOL's to Unix format.

**Comment by Underdog-01** [comment]
If you use Notepad++, it is very easy to change the EOL's.

Open the file -> Edit -> EOL Conversion -> Unix (LF) -> SAVE

also for whitespace at the end of the lines:

Edit -> Blank Operations -> Trim Trailing Space -> SAVE

**Comment by tinoest** [comment]
> Some files have Windows EOL's while others have Unix EOL's.
> 
> Every file should have Unix EOL's.
> All developers should have their editor set to use Unix EOL's as default and the existing files need to be edited to change the EOL's to Unix format.

We don’t have a policy on line endings, I agree Linux EOL makes most sense but we’re tolerant so that \ r, \ n and \ r \ n are allowed.

**Comment by Underdog-01** [comment]
Each LF line ending is 1 byte smaller than CRLF although I suppose that doesn't amount to much.
SMF native files use LF overall.

Off hand I don't have an example of how files with mixed line ending types can cause a problem. 
I hope that mixing the two will not somehow cause problems with SMF, TP or other mods when css & js are loaded on the page.

**Comment by Bopske** [comment]
I’m a sucker for clean coding, but this sounds a bit trivial... if there are no issues with is and you cannot come up with a situation where this would be an issue I do not really see the point tbf ( but I’m not a real coder ...)

**Comment by tinoest** [comment]
> Each LF line ending is 1 byte smaller than CRLF although I suppose that doesn't amount to much.
> SMF native files use LF overall.
> 
> Off hand I don't have an example of how files with mixed line ending types can cause a problem.
> I hope that mixing the two will not somehow cause problems with SMF, TP or other mods when css & js are loaded on the page.

Could you let me know which files aren't Linux? I just did a recursive grep on my Linux box and it hasn't found any .php with Windows line endings. I pushed all the files through dos2unix and no changes were made either. 

`find . -type f -name "*.php" -exec dos2unix {} +`

> > root@tinyportal:/home/tino/TinyPortal# find . -type f -name "*.php" -exec dos2unix {} +
> dos2unix: converting file ./install.php to Unix format...
> dos2unix: converting file ./Sources/TPListImages.php to Unix format...
> dos2unix: converting file ./Sources/TPCompat.php to Unix format...
> dos2unix: converting file ./Sources/TPortalAdmin.php to Unix format...
> dos2unix: converting file ./Sources/TPSearch.php to Unix format...
> dos2unix: converting file ./Sources/TPSSI.php to Unix format...
> dos2unix: converting file ./Sources/TPSubs.php to Unix format...
> dos2unix: converting file ./Sources/TPdlmanager.php to Unix format...
> dos2unix: converting file ./Sources/TPhelp.php to Unix format...
> dos2unix: converting file ./Sources/TPortal.php to Unix format...
> dos2unix: converting file ./Sources/TPcommon.php to Unix format...
> dos2unix: converting file ./Sources/TPArticle.php to Unix format...
> dos2unix: converting file ./Sources/TPBlock.php to Unix format...
> dos2unix: converting file ./Sources/TPShout.php to Unix format...
> dos2unix: converting file ./tp-images/dlmanager/listing/index.php to Unix format...
> dos2unix: converting file ./tp-images/dlmanager/index.php to Unix format...
> dos2unix: converting file ./tp-images/dlmanager/thumb/index.php to Unix format...
> dos2unix: converting file ./tp-images/thumbs/index.php to Unix format...
> dos2unix: converting file ./tp-images/index.php to Unix format...
> dos2unix: converting file ./tp-files/tp-blockcodes/index.php to Unix format...
> dos2unix: converting file ./tp-files/tp-articles/imported/index.php to Unix format...
> dos2unix: converting file ./tp-files/tp-articles/illustrations/index.php to Unix format...
> dos2unix: converting file ./tp-files/tp-articles/index.php to Unix format...
> dos2unix: converting file ./tp-files/tp-articles/images/index.php to Unix format...
> dos2unix: converting file ./tp-files/index.php to Unix format...
> dos2unix: converting file ./Themes/default/TParticle.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPhelp.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPShout.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPdladmin.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPdlmanager.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPprofile.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPortal.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPortalAdmin.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPwireless.template.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPhelp.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPortalAdmin.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPhelp.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPortal.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TParticle.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPdlmanager.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPortalAdmin.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPListImages.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TParticle.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPmodules.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPortal.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPListImages.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPdlmanager.english.php to Unix format...
> dos2unix: converting file ./Themes/default/languages/TPmodules.english-utf8.php to Unix format...
> dos2unix: converting file ./Themes/default/TPprint.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPBlockLayout.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPsubs.template.php to Unix format...
> dos2unix: converting file ./Themes/default/TPSearch.template.php to Unix format...
> dos2unix: converting file ./Themes/default/scripts/tinyportal/index.php to Unix format...
> dos2unix: converting file ./TinyPortal/Admin.php to Unix format...
> dos2unix: converting file ./TinyPortal/Article.php to Unix format...
> dos2unix: converting file ./TinyPortal/Shout.php to Unix format...
> dos2unix: converting file ./TinyPortal/Database.php to Unix format...
> dos2unix: converting file ./TinyPortal/Block.php to Unix format...
> dos2unix: converting file ./TinyPortal/Upload.php to Unix format...
> dos2unix: converting file ./TinyPortal/Base.php to Unix format...
> dos2unix: converting file ./TinyPortal/Mentions.php to Unix format...
> dos2unix: converting file ./TinyPortal/Integrate.php to Unix format...
> dos2unix: converting file ./TinyPortal/Util.php to Unix format...
> dos2unix: converting file ./do_hooks.php to Unix format...
> dos2unix: converting file ./TPStandalone.php to Unix format...
> root@tinyportal:/home/tino/TinyPortal# git status
> On branch development
> Your branch is ahead of 'origin/development' by 8 commits.
>   (use "git push" to publish your local commits)
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	apt.gpg
> 
> nothing added to commit but untracked files present (use "git add" to track)

**Comment by Underdog-01** [comment]
The development version seems fine as I just checked many of its files.
It seems I was looking at a release version 2.0.1 in my Download directory because that one has the mixed content.

My apologies, it appears as though someone already fixed it in the development branch possibly before I mentioned anything.

**Comment by Underdog-01** [comment]
.. unless what you just did there fixed it.
I didn't know GIT let you change that recursively and because of that I was going to use Unix (CentOS) to do it via the command line. I suppose I could have used my Windows command prompt as well. Nice one!
