### ISSUE TITLE
Duplicate language files are unnecessary 

### ISSUE THREAD

**Issue by Underdog-01** [Tinyportal/TinyPortal#831]
Having 2 sets of language files is unnecessary.
You only need the single set without the utf-8 suffix although the files you use should be utf-8 encoded.
This will reduce the overall size of TP.

If you take a look at most recent updated mods and SMF itself, you will see that they stopped using the 2 sets of files long ago.

**Comment by Bopske** [comment]
True, for english they are not needed. I'll drop these completely from the install package.

But what about translated forums in SMF2.0? The utf8 version of those language files will have to remain in their language packs, or the user of a-utf8 forum will end up with English texts in all TP related areas...

Or am I missing something here?

**Comment by Underdog-01** [comment]
You can change those language packs to just use the one file (in utf-8 encoding) but it's not really necessary.
When you use the loadLanguage command in your code, SMF should search for the appropriate language file and failing that it will then load the TP english file.

You can always experiment with just 1 language pack to see if it works as intended.

**Comment by Bopske** [comment]
Fixed by #832
