### ISSUE TITLE
Wrong link target in Profile=>Articles section

### ISSUE THREAD

**Issue by Hatshepsut71** [Tinyportal/TinyPortal#868]
Hello,

I'm using Tinyportal 2.1 on SMF 2.1 RC4 forum.
When I view my profile and navigate to 'Tinyportal=>Articles' section, article category name is described correctly, but link target is wrong.

I will give an example with one screenshot.
The link target of the hovered category is "https://bg-nacionalisti.org/BNF/index.php?mycat=13" (as is displayed in browser status bar), but correct URL must be "https://bg-nacionalisti.org/BNF/index.php?cat=13"
As a result, clicking on this link goes to the main forum page, not to my blog category.

![2021-09-12 (1)](https://user-images.githubusercontent.com/68983397/132974561-eabdc029-9679-42ea-bb6b-4616c425ce4c.png)

**Comment by Bopske** [comment]
Confirmed. To fix: open TPSubs.php

Find this code:
					'category' => '<a href="'.$scripturl.'?mycat='.$row['category'].'">' . (isset($context['TPortal']['catnames'][$row['category']]) ? $context['TPortal']['catnames'][$row['category']] : '') .'</a>',

And change "mycat='.$row['category']" to "cat='.$row['category']"

**Comment by Hatshepsut71** [comment]
Thanks, with this fix problem is solved :)
