### ISSUE TITLE
Too many queries on the frontpage

### ISSUE THREAD

**Issue by dragomano** [Tinyportal/TinyPortal#876]
#### Description
When I was checking the "Only forum-topics" option, I was getting "Page created in 0.250 seconds with 622 queries".

### Steps to reproduce
1. Install the latest SMF version from the Github
2. Install TinyPortal 2.1.0
3. Go to Settings & Frontpage => Frontpage and set up these settings:

- What to display on frontpage => Only forum-topics
- Articles layout for the frontpage = A
- Layout type => normal articles
- Number of articles/topics to display on frontpage => 5
- Show avatars in forum-topics => yes

### Environment (complete as necessary)
- SMF version/Git revision: 2.1 RC4, 9cf0a6e
- Database Type: MariaDB
- Database Version: 10.6.5
- PHP Version: 7.4.26

**Comment by tinoest** [comment]
What queries are shown? Also what blocks are enabled? I get the following with the default install and choosing Only Forum-topics.  

```
Browser ID: firefox (is_firefox95, is_firefox, is_gecko)
Templates: 6: index (default), TPsubs (default), TPBlockLayout (default), TPortal (default), TPShout (default), TPShout (default).
Sub templates: 8: init, html_above, body_above, tp_above, main, tp_below, body_below, html_below.
Language files: 5: index+Modifications.english (default), TPortal.english (default), Stats.english (default), Post.english (default), Editor.english (default).
Style sheets: 4: index.css, jquery.custom-scrollbar.css, jquery.sceditor.css, responsive.css.
Hooks called: 78 (show)
Files included: 48 - 1924KB. (show)
Memory used: 2071KB.
Tokens: post-admin-login.
Queries used: 41.
```

**Comment by dragomano** [comment]
https://drive.google.com/file/d/1agKUlQKYBkJfe9PrBgBoS5d5cM79oCiK/view?usp=sharing

**Comment by dragomano** [comment]
I got the same error on another forum, with 21 boards, and MySQL 5.7.  The option "Display forum-topics on frontpage from" directly affects the number of queries.

**Comment by tinoest** [comment]
I can see how it would as it gets the avatar information and any attachments for each post. I can cache the member information so if as post was from the same user in two different posts it reduces the queries. As we leverage a lot of the internals of SMF and I would prefer to keep it that way we are limited by now much we can reduce it as a lot of them are generated by functions within SMF itself. 

I also question how much of an issue this is when the forum load time is still so low. The query count is high but they appear to be efficient and utilise indexes correctly.

**Comment by tinoest** [comment]
This is reduced in https://github.com/Tinyportal/TinyPortal/pull/875/commits/6dd7dc45aceb0bf2c8e43e87557c5aeb8378c2cb so that we only call those functions if the memberContext does'nt already exist.
