### ISSUE TITLE
PHP 8.1 error Profile view articles

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#911]
Access the my articles page from the profile:

https://localhost/vanilla/index.php?action=profile;area=tparticles;u=3
 [C:/xampp/htdocs/vanilla/Sources/TPSubs.php](https://localhost/vanilla/index.php?action=admin;area=logs;sa=errorlog;file=QzoveGFtcHAvaHRkb2NzL3ZhbmlsbGEvU291cmNlcy9UUFN1YnMucGhw;line=2808) (Line 2808)

Notice
: explode(): Passing null to parameter #2 ($string) of type string is deprecated in
C:\xampp\htdocs\vanilla\Sources\TPSubs.php
on line
2808

code

<html>
<body>

2804: | if($smcFunc['db_num_rows']($request) > 0){
-- | --
2805: | while($row = $smcFunc['db_fetch_assoc']($request)) {
2806: | $rat = array();
2807: | $rating_votes = 0;
==>2808: | $rat = explode(',', $row['rating']);
2809: | $rating_votes = count($rat);
2810: | if($row['rating'] == '') {
2811: | $rating_votes = 0;
2812: | }

</body>
</html>

**Comment by Bopske** [comment]
solution?

$rat = explode(',', (string)$row['rating']);

or 

$rat = explode(',', $row['rating'] ?? ' ');

which one is better? 
note: must m=be supported from PHP7.0.0 onwards

**Comment by tinoest** [comment]
$rat = !is_null($row['rating']) ?  explode(',', $row['rating']) : 0;

**Comment by Bopske** [comment]
> $rat = !is_null($row['rating']) ? explode(',', $row['rating']) : 0;

I used this,

$rat = explode(',', $row['rating'] ?? ' ');

?? is supported from PHP7.0.
Do you see any issues with that?

**Comment by tinoest** [comment]
I personally can’t see an issue today, if PHP decide to throw a error on an empty string it will.

I’ve done it the way I put in other places so consistency should be we do one or the other. I personally don’t like having conditionals inside functions as it can be harder to track down an error, but functionally your way will work.
