### ISSUE TITLE
Possibly undefined constants

### ISSUE THREAD

**Issue by live627** [Tinyportal/TinyPortal#937]
https://github.com/Tinyportal/TinyPortal/blob/1d50f7267a14079a2284485a1d74a620a0c281cf/Sources/TPBlock.php#L83-L103

I quickly searched one and it didn't find the definition https://github.com/Tinyportal/TinyPortal/search?q=TP_BLOCK_ARTICLEBOX

From https://www.simplemachines.org/community/index.php?msg=4141626 (open image in new tab)

**Comment by tinoest** [comment]
Have a look in the construct in Block.php

**Comment by tinoest** [comment]
https://github.com/Tinyportal/TinyPortal/blob/1d50f7267a14079a2284485a1d74a620a0c281cf/TinyPortal/Block.php#L130
