### ISSUE TITLE
Article search: Adding the permission to turn it off for non-approved articles

### ISSUE THREAD

**Issue by isaak654** [Tinyportal/TinyPortal#946]
I would like a new option in TinyPortal to turn off the article search for anyone who has only non-approved articles.

Mentioned by @tinoest in https://github.com/Tinyportal/TinyPortal/pull/945#issuecomment-1370147302
> This should be done before we render the search template. I’d add an additional permission to enable/disable searching. 
> 
> i.e tp_can_search. I can’t see how to create an issue from a PR on mobile view but it’s a good idea.

**Comment by tinoest** [comment]
I don’t quite understand what you mean. I’m not sure if English is your first language, however what you’ve requested doesn’t make sense.

**Comment by isaak654** [comment]
If you had visited my GitHub profile, you would have realised that I'm currently maintaining an Italian website (basic stuff, really).

Above the standard SMF search, TinyPortal adds a new search table in the following page: `forum/index.php?action=search`:

<img src="https://user-images.githubusercontent.com/12372772/210441031-f718a24c-7771-4656-9f20-bae26668d90e.png" height="250px" alt="article_search_table">

I would like an option to turn it off when all TinyPortal articles are not in an approved state:
<img src="https://user-images.githubusercontent.com/12372772/210431389-494ad900-bc97-4c27-a685-44b29190306f.png" height="250px" width="600px" alt="article_view">

Alternatively, feel free not to make this distinction and just add an option to turn off / turn on the article search provided by TinyPortal.

**Comment by tinoest** [comment]
Ahh ok, I understand now. That’s actually logical. 

Didn’t mean to offend, was just confused with the request. Also just replying to the email notification, so not clicked on your profile.

**Comment by isaak654** [comment]
> Didn’t mean to offend, was just confused with the request. 

No problem, but I would suggest you to improve your manners in such a situation.

**Comment by tinoest** [comment]
> > Didn’t mean to offend, was just confused with the request.
> 
> No problem, but I would suggest you to improve your manners in such a situation.

What I said was perfectly polite. Just because I didn’t check your profile to see what language you speak doesn’t mean that what you said in the first instance didn’t make sense to an English speaker.

**Comment by isaak654** [comment]
I would appreciate if you could clear up what I wrote wrong so I could improve next time.

I can assure you that this is not the first time you have behaved rudely.. in any case, feel free to take my suggestion or not.

**Comment by tinoest** [comment]
> I would appreciate if you could clear up what I wrote wrong so I could improve next time.
> 
> I can assure you that this is not the first time you have behaved rudely.. in any case, feel free to take my suggestion or not.

Can you please reference where else I have behaved rudely?

I think your suggestion is very logical and makes sense. So will look to implement it.
