### ISSUE TITLE
Is there a way to turn off the TinyPortal menu shown in other users profiles?

### ISSUE THREAD

**Issue by isaak654** [Tinyportal/TinyPortal#950]
I noticed that any registered user in TinyPortal can view a TinyPortal drop-down menu in the other users' profiles. 
Is it possible to avoid showing it (including the "Tinyportal" button itself)?

Right now, my only use of TinyPortal is to show the topics posted in different boards, so I don't need all functionalities presented in the drop-down menu.

<img src="https://user-images.githubusercontent.com/12372772/212190503-2f98688f-e03e-49a0-8a32-2e8e2cd8101e.png" alt="TinyPortal_button_profile" height="190px">

I found the answer here: https://www.simplemachines.org/community/index.php?msg=4143085

**Comment by Bopske** [comment]
Please post your questions in the TinyPortal support forum so we keep the support requests visible to all and use GitHub for issues and developments

**Comment by Bopske** [comment]
sorry? why the dislike resonse? That's the way we like to manage our support requests...

**Comment by isaak654** [comment]
If you prefer, I can edit this as a feature request, but I would need confirmation from you.

**Comment by Bopske** [comment]
Confirmation of what?

**Comment by isaak654** [comment]
Confirmation that this is a missing functionality or not.

**Comment by Bopske** [comment]
That is exactly the type of discussion for which we have a support forum, hence my request to place it there...
