### ISSUE TITLE
Admin can see all blocks setting not fully working

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#958]
I tested again this morning and as far as I can see now, it is working as I described for blocks in the front panel, but not for the other panels: the blocks are not showing for an administrator even if he has the additional membergroups, except for the front panel

When I tested yesterday I was using a user that had a regular membergroup as the main group, and the administrator as an extra group: then it works as I decribed

Something is definately off here for user that have admin as main membergroup...

**Comment by Bopske** [comment]
Hmm, in the Block.php there is this code: I suspect this is where it goed wrong.
@tinoest , why is there no consequence after checking the 'admin_showblocks'?

Not sure what this check is doing now...

`   public function getBlockPermissions( ) {{{
        global $context, $user_info;

        $blocks = array();
        $user   = reset($user_info['groups']);

        $activeBlocks = $this->getActiveBlocks();
        foreach($activeBlocks as $block) {
            // Check group access
            if(allowedTo('tp_blocks') && (!empty($context['TPortal']['admin_showblocks']) || !isset($context['TPortal']['admin_showblocks']))) {

            }
            else if(empty($block['access'])) {
                continue;
            }
            else if(in_array($user, explode(',', $block['access'])) == false) {
                continue;
            }

            // check page settings
            $display = explode(',', $block['display']);
            if( $this->checkDisplayBlock( $display ) !== TRUE ) {
                continue;
            }

            $blocks[] = $block;
        }

        return $blocks;`

**Comment by tinoest** [comment]
It’s always been that way from what I can tell?

If you disable admin view blocks then I’d expect all blocks to be disabled to an admin as that’s what you’ve checked.

**Comment by Bopske** [comment]
If that's how it is supposed to work, it means that the front panel is broken: that shows the blocks to admin even when the setting is disabled...

**Comment by tinoest** [comment]
The front panel isn’t classed as a block for some reason, I’m not sure why that is historically. Technically it’s not.

**Comment by Bopske** [comment]
Yeah, for some reason the front panel is always using its own code, so as it stands the front panel blocks are showing to admins even the setting would suggest it should not. Do you have an idea where this goes wrong?

**Comment by tinoest** [comment]
I think what it’s doing is correct?

If you add a continue in the first if it’ll miss the block

**Comment by Bopske** [comment]
? The front panel blocks do not even go through this code.

Not sure I understand your suggestion

**Comment by Bopske** [comment]
Even though it may have been like this forever, the way the setting works is a bit counter intuitive.

What I would expect as a user is that I can set the permissions at block level for all user groups, including administrators.
I cannot, because the administrators group is not in the list (could not figure out why not)

The the setting 'admin can see all blocks' would effectively overrule the block specific permissions: if set, the admin would see all blocks, if not set only the blocks where he has block permissions.

But since the administrators group is missing in the block permissions...

**Comment by tinoest** [comment]
I don't think it is, as an admin you either see all blocks or you can disable it so you see none. That is was the setting does.

Admin's aren't in the permission list as they have overriding control over everything in SMF world. i.e. can see and do everything. On the forum I run we have an admin account which can do everything, then every other account is limited, including my own. I have more rights than moderators but still if I want to do 'admin' things I log in as the admin. That is good practice and actively encouraged within Linux where you have a root, sudo and standard users.

**Comment by tinoest** [comment]
So the functionality matches both front panel and blocks you need the following. 

Edit: updated the code, there is a subtle bug that if you only have one group allowed access the explode doesn't work. 

```
    public function getBlockPermissions( ) {{{
        global $context, $user_info;

        $blocks = array();
        $user   = $user_info['groups'];
        $activeBlocks = $this->getActiveBlocks();
        foreach($activeBlocks as $block) {
            // Check group access
            if(allowedTo('tp_blocks') && (!empty($context['TPortal']['admin_showblocks']) || !isset($context['TPortal']['admin_showblocks']))) {
            
            }
            else if(!isset($block['access'])) {
                continue;
            }   
            else if(isset($block['access']) && (strpos($block['access'],',') === false) && (empty(array_intersect(array($block['access']), $user))) ) {
                continue;
            }   
            else if(array_intersect($user, explode(',', $block['access'])) == false) {
                continue;
            }   
            
            // check page settings
            $display = explode(',', $block['display']);
            if( $this->checkDisplayBlock( $display ) !== TRUE ) {
                continue;
            }   
            
            $blocks[] = $block;
        }   
        
        return $blocks;
        
    }}} 
```
