### ISSUE TITLE
<textarea> in html block text makes the text after closing ,/textarea> disappear

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#965]
Seems there are some strange features in the html editor for blocks:

When the user puts a <textarea> in the body of an html block, the body text is cut just before the closing </textarea>

Reported here:
https://www.simplemachines.org/community/index.php?msg=4146570

and I confirmed it: put below text in a HTML block and save to see the result

[code]
<textarea name="affiliates">Some text</text area>
<img src="https://www.tinyportal.net/Themes/alphacentauri203/images/theme/logo_light.png>"
[/code]

**Comment by tinoest** [comment]
Using textarea makes no sense in a wysiwyg. What is the use case for this?

Does SMF exhibit the same issue if you create a topic?

**Comment by Bopske** [comment]
There is no wysiwyg on html blocks. So effectively the user is just applying any html. What he is doing could be easily accomplished with a bbc block and I told him so.

Still text area is valid html code, and the block then cutting off the html code us u expected

**Comment by tinoest** [comment]
We don’t have the option to input data from a block. This is user error. 

https://www.w3schools.com/tags/tag_textarea.asp

**Comment by Bopske** [comment]
wow, you are quick to close this: I agree that the use of textarea is debateble but it STILL is valid html, that is being cut short by TinyPortal...

Perhaps you can explain why this is expected behaviour to the reporter? I cannot

**Comment by tinoest** [comment]
Textarea is used to input data. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

What is happening is expected behaviour, if you want it to work differently speak to Mozilla, Google or Apple.
