### ISSUE TITLE
Block visibility depending on the theme

### ISSUE THREAD

**Issue by Vanok179** [Tinyportal/TinyPortal#974]
The ability to hide blocks on certain themes is very lacking

**Comment by Bopske** [comment]
I am not sure I agree to this: themes are a different visual presentation of the content. They are not typically controlling the content.

I do see that some themes implement 'blocks' of information themselves, like recent posts of links, which may replace TinyPortal block functions, but making blocks theme dependent may be a bit much..,

**Comment by tinoest** [comment]
Can you provide some context behind why it’s lacking?

As @Bopske said a theme is a way to display content, not control the content.

**Comment by Vanok179** [comment]
Strange questions. Why some people using wet wipes instead of toilet paper? Because they are more comfortable! Just because you don't need something doesn't mean that others don't. 

Specifically, in this case, some blocks may be oriented to a specific panel layout. For example I have 2 themes: one with two panels and the other with one. In order not to create crutches, it's easier for me to make duplicate blocks in the right location and show them depending on the chosen theme.

**Comment by tinoest** [comment]
If you feel that way, you are welcome to make the required changes and submit a pull request for us to review. 

This sounds more like a problem with your themes than a problem with TinyPortal, however I see the validity and as mentioned above you are welcome to submit the PR with the changes.

**Comment by Bopske** [comment]
If you find our questions strange, you may need to consider you are raising your request as an 'issue'. Typically we tend to try and understand any issue raised. 

That's why we are asking questions. If you feel your issue to be a big lack of functionality we of course welcome all contributions to improve.

**Comment by Vanok179** [comment]
> This sounds more like a problem with your themes than a problem with TinyPortal

No. This is precisely the lack of functionality of the portal.  In my opinion of corse.
This, once again I explain, that it would be worth giving the opportunity to show a different set of blocks on different themes. If it seems to you that this is not the necessary functionality, I just want to remind you that there are mobile themes and on mobile devices those blocks that are not needed on ordinary ones (and vice versa) can be used.
Of course I do not demand "do it now" - I just draw attention to the possibility of improving the functionality

**Comment by tinoest** [comment]
That is fair enough, but we have a layout for mobile views which to my knowledge no one has complained about before now. The main complaint we have is that TinyPortal is actually too complex with what you can do regarding enabling blocks, this would make it even more complex. Especially as you want to do it via duplicate blocks. 

I’ll reiterate, you are welcome to make the required changes and submit a PR to resolve what you feel is lacking functionality.

**Comment by Bopske** [comment]
Just wondering what SMF version you are aiming for? We do not plan to develop for SMF2.0 anymore and all 2.1 themes are responsive, so not 'mobile' specific. Do you see this issue with 2.1? If so, I would be interested to know what themes you are using, to experiment with..

**Comment by Vanok179** [comment]
I'm using 2.0 and handmade mobile theme. Anyway thank you for answer
